### ISSUE TITLE
[boost]: Missing log_setup in lib_list

### ISSUE THREAD

**Issue by avacore1337** [conan-io/conan-center-index#142]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.69**
  * Operating System+version: **Linux Ubuntu 18.04**

https://github.com/conan-io/conan-center-index/blob/a34458e886d2b5c1d0e3a091a559d281644631d5/recipes/boost/all/conanfile.py#L20

log_setup.a is provided by the package but not exported. Simply adding it to the lib_list in front of log fixes the problem.

https://stackoverflow.com/questions/17444059/reason-for-libboost-log-setup-a-library

Seems like it disappeared after switching from a list of libs:
https://github.com/conan-community/conan-boost/commit/20af2e4159a93a351a7c143d8662088e94860b7a

and then back:
https://github.com/conan-community/conan-boost/commit/5cd89111396f8b724394167d3de803f636bc9716

**Comment by SSE4** [comment]
fixed by #2097

**Comment by Hadatko** [comment]
Hello, i have same issue with newest library version. log_setup is still missing in lib_list.
