### ISSUE TITLE
[service] Update wiki to use the new CCI CMake package

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1835]
Right now the wiki is mentioning the old `cmake_installer` package, this should be updated

https://github.com/conan-io/conan-center-index/wiki/FAQ#why-recipes-that-use-build-tools-like-cmake-that-have-packages-in-conan-center-do-not-use-it-as-a-build-require-by-default

**Comment by uilianries** [comment]
done!

**Comment by Croydon** [comment]
You missed the following

>  However, cmake_installer could be useful to use in your profile:

`cmake_installer` -> `cmake` 

and

```
[build_requires]
cmake/....@....
```

is still confusing as there should not be any `@`, so replace it with something accurate and more understandable like  `cmake/1.17.3`? 🤔

**Comment by uilianries** [comment]
My fault! I'll fix it! Thanks @Croydon !

**Comment by uilianries** [comment]
Done Done! :D

**Comment by Croydon** [comment]
Thanks! 😄
