### ISSUE TITLE
[package] `cryptopp-pem`, `microprofile`, `nas` and `tweetnacl` recipes broken because https://unlicense.org is down since July

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#19951]
### Description

`cryptopp-pem`, `microprofile`, `nas` and `tweetnacl` recipes download an extra file from https://unlicense.org but this website is down since July: https://github.com/unlicense/unlicense.org/issues/89

Therefore they can't be built from source anymore since `source()` method fails to download this file.

### Logs

```
nas/1.9.4: ERROR: Error downloading file https://unlicense.org/UNLICENSE: 'HTTPSConnectionPool(host='unlicense.org', port=443): Max retries exceeded with url: /UNLICENSE (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)')))'
nas/1.9.4: Waiting 5 seconds to retry...
nas/1.9.4: ERROR: Error downloading file https://unlicense.org/UNLICENSE: 'HTTPSConnectionPool(host='unlicense.org', port=443): Max retries exceeded with url: /UNLICENSE (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)')))'
nas/1.9.4: Waiting 5 seconds to retry...
ERROR: nas/1.9.4: Error in source() method, line 65
        download(self, filename="LICENSE", **self.conan_data["sources"][self.version][1])
        ConanException: Error downloading file https://unlicense.org/UNLICENSE: 'HTTPSConnectionPool(host='unlicense.org', port=443): Max retries exceeded with url: /UNLICENSE (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)')))'
```

**Comment by RubenRBS** [comment]
Progress (Still need to push the branches):
* nas -> fixed
* microprofiles -> actually uses unlicense from the repo, keeping as-is (But needs porting to v2!)
* tweetnacl -> same as microprofiles
* cryptopp-pem -> same as last 2

**Comment by RubenRBS** [comment]
I'm just now seeing that CCI might not be correctly using the `LicenseRef` SPDX attribute, I'll double check with the team, thanks for bringing this up to our attention though

**Comment by Krakada** [comment]
Hi @RubenRBS , sorry but I'm not sure that I got you comment about cryptopp-pem (and the 2 others): is there a plan to fix this download failure? If not, are you aware of any workaround to this issue?

Thanks in advance for your help.

**Comment by RubenRBS** [comment]
Yes, sorry, I only partially fixed this, you're totally tight that it's still blocked - I only checked on the licenses themselves being valid, but did not fix the missing link, will push an update for those recipes now, thanks for the ping!

**Comment by RubenRBS** [comment]
Okey, I've now pushed proper fixes for the recipes, thanks a lot again for double checking @Krakada 
As for tweetnacl, it's an interesting case, will double check with the team about the best approach

**Comment by Krakada** [comment]
Hi Ruben, thanks a lot for your help!

Once it will be merged, don't hesitate to ping me if you want me to test it.

Cheers,

**Comment by Krakada** [comment]
Hi @RubenRBS, sorry to bother you again, but could you confirm whether the fix was made available?

It seems that it is still not working for me, but I might not be testing it in the right way (I'm not sure whether it is important, but note that I've not yet migrated to Conan v2).

Thanks in advance for your help.

**Comment by RubenRBS** [comment]
Sure, give me a few minutes and I'll get back to you @Krakada :)

**Comment by RubenRBS** [comment]
Ok I now see what's happening here: Yes! Most recipes were fixed, but we saw an opprtunity with cryptopem to update it to v2 in https://github.com/conan-io/conan-center-index/pull/18863, which has not quite yet been merged, but @czoido has been working hard on getting it thru the finish line today so I would expect it to be merged soon, we'll ping you when so
