### ISSUE TITLE
[package] m4/1.4.18 won't build on x86

### ISSUE THREAD

**Issue by jmarrec** [conan-io/conan-center-index#2183]
I'm indirectly using m4 because I'm trying to upgrade from `bison_installer/3.3.2@bincrafters/stable` (which doesn't use m4) to `bison/3.5.3`. The build fails on win32

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **m4/1.4.18**
  * Operating System+version: **Windows, trying to compile x86**
  * Compiler+version: **MSVC 2019**
  * Docker image: **Visual Studio 2019**
  * Conan version: **conan 1.27.1**
  * Python version: **Python 3.7**

```
+-----+--------------------+--------------------+--------------+---------------+--------+
|   # | compiler.runtime   |   compiler.version | build_type   | compiler      | arch   |
|-----+--------------------+--------------------+--------------+---------------+--------|
|   1 | MD                 |                 16 | Release      | Visual Studio | x86    |
+-----+--------------------+--------------------+--------------+---------------+--------+
```

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
+------------------------+
| Profile                |
|------------------------|
| include(default)       |
|                        |
| [settings]             |
| arch=x86               |
| build_type=Release     |
| compiler=Visual Studio |
| compiler.runtime=MD    |
| compiler.version=16    |
| [options]              |
|                        |
| [env]                  |
|                        |
| [build_requires]       |
+------------------------+
[conan_create]

```

### Logs (Include/Attach if Applicable)

https://ci.appveyor.com/project/ci-commercialbuildings/conan-openstudio-ruby/builds/34022248/job/cwpdsxi4huylrr92#L614

<details><summary>Click to expand log</summary>

```
Downloading conan_sources.tgz
m4/1.4.18: Configuring sources in C:\Users\appveyor\.conan\data\m4\1.4.18\_\_\source
m4/1.4.18: Copying sources to build folder
m4/1.4.18: Building your package in C:\Users\appveyor\.conan\data\m4\1.4.18\_\_\build\b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3
m4/1.4.18: Generator txt created conanbuildinfo.txt
m4/1.4.18: Calling build()
Conan:vcvars already set 
m4/1.4.18: run_in_windows_bash: "C:\Program Files\Git\usr\bin\bash.exe" --login -c ^"cd \^"/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3\^" ^&^& /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure --help ^"
m4/1.4.18: `configure' configures GNU M4 1.4.18 to adapt to many kinds of systems.
m4/1.4.18: 
m4/1.4.18: Usage: /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure [OPTION]... [VAR=VALUE]...
m4/1.4.18: 
m4/1.4.18: To assign environment variables (e.g., CC, CFLAGS...), specify them as
m4/1.4.18: VAR=VALUE.  See below for descriptions of some of the useful variables.
m4/1.4.18: 
m4/1.4.18: Defaults for the options are specified in brackets.
m4/1.4.18: 
m4/1.4.18: Configuration:
m4/1.4.18:   -h, --help              display this help and exit
m4/1.4.18:       --help=short        display options specific to this package
m4/1.4.18:       --help=recursive    display the short help of all the included packages
m4/1.4.18:   -V, --version           display version information and exit
m4/1.4.18:   -q, --quiet, --silent   do not print `checking ...' messages
m4/1.4.18:       --cache-file=FILE   cache test results in FILE [disabled]
m4/1.4.18:   -C, --config-cache      alias for `--cache-file=config.cache'
m4/1.4.18:   -n, --no-create         do not create output files
m4/1.4.18:       --srcdir=DIR        find the sources in DIR [configure dir or `..']
m4/1.4.18: 
m4/1.4.18: Installation directories:
m4/1.4.18:   --prefix=PREFIX         install architecture-independent files in PREFIX
m4/1.4.18:                           [/usr/local]
m4/1.4.18:   --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
m4/1.4.18:                           [PREFIX]
m4/1.4.18: 
m4/1.4.18: By default, `make install' will install all the files in
m4/1.4.18: `/usr/local/bin', `/usr/local/lib' etc.  You can specify
m4/1.4.18: an installation prefix other than `/usr/local' using `--prefix',
m4/1.4.18: for instance `--prefix=$HOME'.
m4/1.4.18: 
m4/1.4.18: For better control, use the options below.
m4/1.4.18: 
m4/1.4.18: Fine tuning of the installation directories:
m4/1.4.18:   --bindir=DIR            user executables [EPREFIX/bin]
m4/1.4.18:   --sbindir=DIR           system admin executables [EPREFIX/sbin]
m4/1.4.18:   --libexecdir=DIR        program executables [EPREFIX/libexec]
m4/1.4.18:   --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
m4/1.4.18:   --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
m4/1.4.18:   --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
m4/1.4.18:   --libdir=DIR            object code libraries [EPREFIX/lib]
m4/1.4.18:   --includedir=DIR        C header files [PREFIX/include]
m4/1.4.18:   --oldincludedir=DIR     C header files for non-gcc [/usr/include]
m4/1.4.18:   --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
m4/1.4.18:   --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
m4/1.4.18:   --infodir=DIR           info documentation [DATAROOTDIR/info]
m4/1.4.18:   --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
m4/1.4.18:   --mandir=DIR            man documentation [DATAROOTDIR/man]
m4/1.4.18:   --docdir=DIR            documentation root [DATAROOTDIR/doc/m4]
m4/1.4.18:   --htmldir=DIR           html documentation [DOCDIR]
m4/1.4.18:   --dvidir=DIR            dvi documentation [DOCDIR]
m4/1.4.18:   --pdfdir=DIR            pdf documentation [DOCDIR]
m4/1.4.18:   --psdir=DIR             ps documentation [DOCDIR]
m4/1.4.18: 
m4/1.4.18: Program names:
m4/1.4.18:   --program-prefix=PREFIX            prepend PREFIX to installed program names
m4/1.4.18:   --program-suffix=SUFFIX            append SUFFIX to installed program names
m4/1.4.18:   --program-transform-name=PROGRAM   run sed PROGRAM on installed program names
m4/1.4.18: 
m4/1.4.18: System types:
m4/1.4.18:   --build=BUILD     configure for building on BUILD [guessed]
m4/1.4.18:   --host=HOST       cross-compile to build programs to run on HOST [BUILD]
m4/1.4.18: 
m4/1.4.18: Optional Features:
m4/1.4.18:   --disable-option-checking  ignore unrecognized --enable/--with options
m4/1.4.18:   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
m4/1.4.18:   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
m4/1.4.18:   --enable-silent-rules   less verbose build output (undo: "make V=1")
m4/1.4.18:   --disable-silent-rules  verbose build output (undo: "make V=0")
m4/1.4.18:   --enable-dependency-tracking
m4/1.4.18:                           do not reject slow dependency extractors
m4/1.4.18:   --disable-dependency-tracking
m4/1.4.18:                           speeds up one-time build
m4/1.4.18:   --disable-largefile     omit support for large files
m4/1.4.18:   --enable-threads={posix|solaris|pth|windows}
m4/1.4.18:                           specify multithreading API
m4/1.4.18:   --disable-threads       build without multithread safety
m4/1.4.18:   --enable-gcc-warnings   turn on lots of GCC warnings (for developers)
m4/1.4.18:   --disable-assert        turn off assertions
m4/1.4.18:   --disable-rpath         do not hardcode runtime library paths
m4/1.4.18:   --enable-c++            also build C++ sources
m4/1.4.18:   --enable-changeword     enable -W and changeword() builtin
m4/1.4.18: 
m4/1.4.18: Optional Packages:
m4/1.4.18:   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
m4/1.4.18:   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
m4/1.4.18:   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
m4/1.4.18:   --with-libsigsegv-prefix[=DIR]  search for libsigsegv in DIR/include and DIR/lib
m4/1.4.18:   --without-libsigsegv-prefix     don't search for libsigsegv in includedir and libdir
m4/1.4.18:   --with-libpth-prefix[=DIR]  search for libpth in DIR/include and DIR/lib
m4/1.4.18:   --without-libpth-prefix     don't search for libpth in includedir and libdir
m4/1.4.18:   --without-included-regex
m4/1.4.18:                           don't compile regex; this is the default on systems
m4/1.4.18:                           with recent-enough versions of the GNU C Library
m4/1.4.18:                           (use with caution on other systems).
m4/1.4.18:   --with-packager         String identifying the packager of this software
m4/1.4.18:   --with-packager-version Packager-specific version information
m4/1.4.18:   --with-packager-bug-reports
m4/1.4.18:                           Packager info for bug reports (URL/e-mail/...)
m4/1.4.18:   --with-syscmd-shell     shell used by syscmd [/bin/sh]
m4/1.4.18:   --with-dmalloc          use dmalloc, as in dmalloc.tar.gz from
m4/1.4.18:                           @/ftp.antaire.com:antaire/src/dmalloc.
m4/1.4.18: 
m4/1.4.18: Some influential environment variables:
m4/1.4.18:   CC          C compiler command
m4/1.4.18:   CFLAGS      C compiler flags
m4/1.4.18:   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
m4/1.4.18:               nonstandard directory <lib dir>
m4/1.4.18:   LIBS        libraries to pass to the linker, e.g. -l<library>
m4/1.4.18:   CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
m4/1.4.18:               you have headers in a nonstandard directory <include dir>
m4/1.4.18:   CPP         C preprocessor
m4/1.4.18:   CXX         C++ compiler command
m4/1.4.18:   CXXFLAGS    C++ compiler flags
m4/1.4.18: 
m4/1.4.18: Use these variables to override the choices made by `configure' or to help
m4/1.4.18: it to find libraries and programs with nonstandard names/locations.
m4/1.4.18: 
m4/1.4.18: Report bugs to <bug-m4@gnu.org>.
m4/1.4.18: GNU M4 home page: <http://www.gnu.org/software/m4/>.
m4/1.4.18: General help using GNU software: <http://www.gnu.org/gethelp/>.
m4/1.4.18: Calling:
 > /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure --prefix=C:/Users/appveyor/.conan/data/m4/1.4.18/_/_/package/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3 --build=x86_64-windows-msvc --host=i686-windows-msvc
m4/1.4.18: run_in_windows_bash: "C:\Program Files\Git\usr\bin\bash.exe" --login -c ^"cd \^"/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3\^" ^&^& /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure --prefix=C:/Users/appveyor/.conan/data/m4/1.4.18/_/_/package/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3 --build=x86_64-windows-msvc --host=i686-windows-msvc ^"
m4/1.4.18: checking for a BSD-compatible install... /usr/bin/install -c
m4/1.4.18: checking whether build environment is sane... yes
m4/1.4.18: checking for i686-windows-msvc-strip... :
m4/1.4.18: checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
m4/1.4.18: checking for gawk... gawk
m4/1.4.18: checking whether make sets $(MAKE)... no
m4/1.4.18: checking whether make supports nested variables... no
m4/1.4.18: checking whether make supports nested variables... (cached) no
m4/1.4.18: checking for i686-windows-msvc-gcc... cl -nologo
m4/1.4.18: checking whether the C compiler works... yes
m4/1.4.18: checking for C compiler default output file name... conftest.exe
m4/1.4.18: checking for suffix of executables... .exe
m4/1.4.18: checking whether we are cross compiling... yes
m4/1.4.18: checking for suffix of object files... obj
m4/1.4.18: checking whether we are using the GNU C compiler... no
m4/1.4.18: checking whether cl -nologo accepts -g... no
m4/1.4.18: checking for cl -nologo option to accept ISO C89... none needed
m4/1.4.18: checking whether cl -nologo understands -c and -o together... no
m4/1.4.18: checking for style of include used by make... none
m4/1.4.18: checking dependency style of /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/compile cl -nologo... none
m4/1.4.18: checking how to run the C preprocessor... /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/compile cl -nologo -E
m4/1.4.18: checking for grep that handles long lines and -e... /usr/bin/grep
m4/1.4.18: checking for egrep... /usr/bin/grep -E
m4/1.4.18: checking for ANSI C header files... yes
m4/1.4.18: checking for sys/types.h... yes
m4/1.4.18: checking for sys/stat.h... yes
m4/1.4.18: checking for stdlib.h... yes
m4/1.4.18: checking for string.h... yes
m4/1.4.18: checking for memory.h... yes
m4/1.4.18: checking for strings.h... no
m4/1.4.18: checking for inttypes.h... yes
m4/1.4.18: checking for stdint.h... yes
m4/1.4.18: checking for unistd.h... no
m4/1.4.18: checking minix/config.h usability... no
m4/1.4.18: checking minix/config.h presence... no
m4/1.4.18: checking for minix/config.h... no
m4/1.4.18: checking whether it is safe to define __EXTENSIONS__... yes
m4/1.4.18: checking whether _XOPEN_SOURCE should be defined... no
m4/1.4.18: checking for Minix Amsterdam compiler... no
m4/1.4.18: checking for i686-windows-msvc-ar... /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/ar-lib lib
m4/1.4.18: checking the archiver (/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/ar-lib lib) interface... ar
m4/1.4.18: checking for i686-windows-msvc-ar... (cached) /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/ar-lib lib
m4/1.4.18: checking build system type... Invalid configuration `x86_64-windows-msvc': system `msvc' not recognized
m4/1.4.18: configure: error: /bin/sh /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/config.sub x86_64-windows-msvc failed
m4/1.4.18: 
```

</details>

**Comment by madebr** [comment]
This should be fixed by #2250 

Note that you in your logs, arch=x86.
m4 is only used as a build requirement, so arch_build can be x86_64 and you would not need a x86 m4 package.

**Comment by jmarrec** [comment]
@madebr I still get an error. A different one though, cf : https://ci.appveyor.com/project/ci-commercialbuildings/conan-openstudio-ruby/builds/34345124/job/o4ga9pkt9d1j1ybr

```
m4/1.4.18: config.status: executing stamp-h commands
m4/1.4.18: run_in_windows_bash: "C:\Program Files\Git\usr\bin\bash.exe" --login -c ^"cd \^"/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3\^" ^&^& make -j2 ^"
m4/1.4.18: /usr/bin/bash: make: command not found
```

```
Downloading conan_sources.tgz
m4/1.4.18: Configuring sources in C:\Users\appveyor\.conan\data\m4\1.4.18\_\_\source
m4/1.4.18: Copying sources to build folder
m4/1.4.18: Building your package in C:\Users\appveyor\.conan\data\m4\1.4.18\_\_\build\b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3
m4/1.4.18: Generator txt created conanbuildinfo.txt
m4/1.4.18: Calling build()
Conan:vcvars already set 
m4/1.4.18: run_in_windows_bash: "C:\Program Files\Git\usr\bin\bash.exe" --login -c ^"cd \^"/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3\^" ^&^& /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure --help ^"
m4/1.4.18: `configure' configures GNU M4 1.4.18 to adapt to many kinds of systems.
m4/1.4.18: 
m4/1.4.18: Usage: /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure [OPTION]... [VAR=VALUE]...
m4/1.4.18: 
m4/1.4.18: To assign environment variables (e.g., CC, CFLAGS...), specify them as
m4/1.4.18: VAR=VALUE.  See below for descriptions of some of the useful variables.
m4/1.4.18: 
m4/1.4.18: Defaults for the options are specified in brackets.
m4/1.4.18: 
m4/1.4.18: Configuration:
m4/1.4.18:   -h, --help              display this help and exit
m4/1.4.18:       --help=short        display options specific to this package
m4/1.4.18:       --help=recursive    display the short help of all the included packages
m4/1.4.18:   -V, --version           display version information and exit
m4/1.4.18:   -q, --quiet, --silent   do not print `checking ...' messages
m4/1.4.18:       --cache-file=FILE   cache test results in FILE [disabled]
m4/1.4.18:   -C, --config-cache      alias for `--cache-file=config.cache'
m4/1.4.18:   -n, --no-create         do not create output files
m4/1.4.18:       --srcdir=DIR        find the sources in DIR [configure dir or `..']
m4/1.4.18: 
m4/1.4.18: Installation directories:
m4/1.4.18:   --prefix=PREFIX         install architecture-independent files in PREFIX
m4/1.4.18:                           [/usr/local]
m4/1.4.18:   --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
m4/1.4.18:                           [PREFIX]
m4/1.4.18: 
m4/1.4.18: By default, `make install' will install all the files in
m4/1.4.18: `/usr/local/bin', `/usr/local/lib' etc.  You can specify
m4/1.4.18: an installation prefix other than `/usr/local' using `--prefix',
m4/1.4.18: for instance `--prefix=$HOME'.
m4/1.4.18: 
m4/1.4.18: For better control, use the options below.
m4/1.4.18: 
m4/1.4.18: Fine tuning of the installation directories:
m4/1.4.18:   --bindir=DIR            user executables [EPREFIX/bin]
m4/1.4.18:   --sbindir=DIR           system admin executables [EPREFIX/sbin]
m4/1.4.18:   --libexecdir=DIR        program executables [EPREFIX/libexec]
m4/1.4.18:   --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
m4/1.4.18:   --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
m4/1.4.18:   --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
m4/1.4.18:   --libdir=DIR            object code libraries [EPREFIX/lib]
m4/1.4.18:   --includedir=DIR        C header files [PREFIX/include]
m4/1.4.18:   --oldincludedir=DIR     C header files for non-gcc [/usr/include]
m4/1.4.18:   --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
m4/1.4.18:   --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
m4/1.4.18:   --infodir=DIR           info documentation [DATAROOTDIR/info]
m4/1.4.18:   --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
m4/1.4.18:   --mandir=DIR            man documentation [DATAROOTDIR/man]
m4/1.4.18:   --docdir=DIR            documentation root [DATAROOTDIR/doc/m4]
m4/1.4.18:   --htmldir=DIR           html documentation [DOCDIR]
m4/1.4.18:   --dvidir=DIR            dvi documentation [DOCDIR]
m4/1.4.18:   --pdfdir=DIR            pdf documentation [DOCDIR]
m4/1.4.18:   --psdir=DIR             ps documentation [DOCDIR]
m4/1.4.18: 
m4/1.4.18: Program names:
m4/1.4.18:   --program-prefix=PREFIX            prepend PREFIX to installed program names
m4/1.4.18:   --program-suffix=SUFFIX            append SUFFIX to installed program names
m4/1.4.18:   --program-transform-name=PROGRAM   run sed PROGRAM on installed program names
m4/1.4.18: 
m4/1.4.18: System types:
m4/1.4.18:   --build=BUILD     configure for building on BUILD [guessed]
m4/1.4.18:   --host=HOST       cross-compile to build programs to run on HOST [BUILD]
m4/1.4.18: 
m4/1.4.18: Optional Features:
m4/1.4.18:   --disable-option-checking  ignore unrecognized --enable/--with options
m4/1.4.18:   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
m4/1.4.18:   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
m4/1.4.18:   --enable-silent-rules   less verbose build output (undo: "make V=1")
m4/1.4.18:   --disable-silent-rules  verbose build output (undo: "make V=0")
m4/1.4.18:   --enable-dependency-tracking
m4/1.4.18:                           do not reject slow dependency extractors
m4/1.4.18:   --disable-dependency-tracking
m4/1.4.18:                           speeds up one-time build
m4/1.4.18:   --disable-largefile     omit support for large files
m4/1.4.18:   --enable-threads={posix|solaris|pth|windows}
m4/1.4.18:                           specify multithreading API
m4/1.4.18:   --disable-threads       build without multithread safety
m4/1.4.18:   --enable-gcc-warnings   turn on lots of GCC warnings (for developers)
m4/1.4.18:   --disable-assert        turn off assertions
m4/1.4.18:   --disable-rpath         do not hardcode runtime library paths
m4/1.4.18:   --enable-c++            also build C++ sources
m4/1.4.18:   --enable-changeword     enable -W and changeword() builtin
m4/1.4.18: 
m4/1.4.18: Optional Packages:
m4/1.4.18:   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
m4/1.4.18:   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
m4/1.4.18:   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
m4/1.4.18:   --with-libsigsegv-prefix[=DIR]  search for libsigsegv in DIR/include and DIR/lib
m4/1.4.18:   --without-libsigsegv-prefix     don't search for libsigsegv in includedir and libdir
m4/1.4.18:   --with-libpth-prefix[=DIR]  search for libpth in DIR/include and DIR/lib
m4/1.4.18:   --without-libpth-prefix     don't search for libpth in includedir and libdir
m4/1.4.18:   --without-included-regex
m4/1.4.18:                           don't compile regex; this is the default on systems
m4/1.4.18:                           with recent-enough versions of the GNU C Library
m4/1.4.18:                           (use with caution on other systems).
m4/1.4.18:   --with-packager         String identifying the packager of this software
m4/1.4.18:   --with-packager-version Packager-specific version information
m4/1.4.18:   --with-packager-bug-reports
m4/1.4.18:                           Packager info for bug reports (URL/e-mail/...)
m4/1.4.18:   --with-syscmd-shell     shell used by syscmd [/bin/sh]
m4/1.4.18:   --with-dmalloc          use dmalloc, as in dmalloc.tar.gz from
m4/1.4.18:                           @/ftp.antaire.com:antaire/src/dmalloc.
m4/1.4.18: 
m4/1.4.18: Some influential environment variables:
m4/1.4.18:   CC          C compiler command
m4/1.4.18:   CFLAGS      C compiler flags
m4/1.4.18:   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
m4/1.4.18:               nonstandard directory <lib dir>
m4/1.4.18:   LIBS        libraries to pass to the linker, e.g. -l<library>
m4/1.4.18:   CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
m4/1.4.18:               you have headers in a nonstandard directory <include dir>
m4/1.4.18:   CPP         C preprocessor
m4/1.4.18:   CXX         C++ compiler command
m4/1.4.18:   CXXFLAGS    C++ compiler flags
m4/1.4.18: 
m4/1.4.18: Use these variables to override the choices made by `configure' or to help
m4/1.4.18: it to find libraries and programs with nonstandard names/locations.
m4/1.4.18: 
m4/1.4.18: Report bugs to <bug-m4@gnu.org>.
m4/1.4.18: GNU M4 home page: <http://www.gnu.org/software/m4/>.
m4/1.4.18: General help using GNU software: <http://www.gnu.org/gethelp/>.
m4/1.4.18: Calling:
 > /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure --prefix=C:/Users/appveyor/.conan/data/m4/1.4.18/_/_/package/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3 
m4/1.4.18: run_in_windows_bash: "C:\Program Files\Git\usr\bin\bash.exe" --login -c ^"cd \^"/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3\^" ^&^& /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/configure --prefix=C:/Users/appveyor/.conan/data/m4/1.4.18/_/_/package/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3  ^"
m4/1.4.18: checking for a BSD-compatible install... /usr/bin/install -c
m4/1.4.18: checking whether build environment is sane... yes
m4/1.4.18: checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
m4/1.4.18: checking for gawk... gawk
m4/1.4.18: checking whether make sets $(MAKE)... no
m4/1.4.18: checking whether make supports nested variables... no
m4/1.4.18: checking whether make supports nested variables... (cached) no
m4/1.4.18: checking for gcc... cl -nologo
m4/1.4.18: checking whether the C compiler works... yes
m4/1.4.18: checking for C compiler default output file name... conftest.exe
m4/1.4.18: checking for suffix of executables... .exe
m4/1.4.18: checking whether we are cross compiling... no
m4/1.4.18: checking for suffix of object files... obj
m4/1.4.18: checking whether we are using the GNU C compiler... no
m4/1.4.18: checking whether cl -nologo accepts -g... no
m4/1.4.18: checking for cl -nologo option to accept ISO C89... none needed
m4/1.4.18: checking whether cl -nologo understands -c and -o together... no
m4/1.4.18: checking for style of include used by make... none
m4/1.4.18: checking dependency style of /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/compile cl -nologo... none
m4/1.4.18: checking how to run the C preprocessor... /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/compile cl -nologo -E
m4/1.4.18: checking for grep that handles long lines and -e... /usr/bin/grep
m4/1.4.18: checking for egrep... /usr/bin/grep -E
m4/1.4.18: checking for ANSI C header files... yes
m4/1.4.18: checking for sys/types.h... yes
m4/1.4.18: checking for sys/stat.h... yes
m4/1.4.18: checking for stdlib.h... yes
m4/1.4.18: checking for string.h... yes
m4/1.4.18: checking for memory.h... yes
m4/1.4.18: checking for strings.h... no
m4/1.4.18: checking for inttypes.h... yes
m4/1.4.18: checking for stdint.h... yes
m4/1.4.18: checking for unistd.h... no
m4/1.4.18: checking minix/config.h usability... no
m4/1.4.18: checking minix/config.h presence... no
m4/1.4.18: checking for minix/config.h... no
m4/1.4.18: checking whether it is safe to define __EXTENSIONS__... yes
m4/1.4.18: checking whether _XOPEN_SOURCE should be defined... no
m4/1.4.18: checking for Minix Amsterdam compiler... no
m4/1.4.18: checking the archiver (/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/ar-lib lib) interface... ar
m4/1.4.18: checking for ar... /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/ar-lib lib
m4/1.4.18: checking build system type... x86_64-pc-mingw32
m4/1.4.18: checking host system type... x86_64-pc-mingw32
m4/1.4.18: checking for _LARGEFILE_SOURCE value needed for large files... unknown
m4/1.4.18: checking for special C compiler options needed for large files... no
m4/1.4.18: checking for _FILE_OFFSET_BITS value needed for large files... unknown
m4/1.4.18: checking for _LARGE_FILES value needed for large files... unknown
m4/1.4.18: checking for /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/compile cl -nologo option to accept ISO C99... unsupported
m4/1.4.18: checking for /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/compile cl -nologo option to accept ISO C89... (cached) none needed
m4/1.4.18: checking for /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/build-aux/compile cl -nologo option to accept ISO Standard C... (cached) none needed
m4/1.4.18: configure: autobuild project... GNU M4
m4/1.4.18: configure: autobuild revision... 1.4.18
m4/1.4.18: configure: autobuild hostname... appveyor-vm
m4/1.4.18: configure: autobuild timestamp... 20200728T134303Z
m4/1.4.18: checking for unsigned long long int... yes
m4/1.4.18: checking for long long int... yes
m4/1.4.18: checking for unsigned long long int... (cached) yes
m4/1.4.18: checking for size_t... yes
m4/1.4.18: checking for working alloca.h... no
m4/1.4.18: checking for alloca... yes
m4/1.4.18: checking whether <wchar.h> uses 'inline' correctly... yes
m4/1.4.18: checking for btowc... yes
m4/1.4.18: checking for setrlimit... no
m4/1.4.18: checking for sigaltstack... no
m4/1.4.18: checking for canonicalize_file_name... no
m4/1.4.18: checking for getcwd... yes
m4/1.4.18: checking for readlink... no
m4/1.4.18: checking for realpath... no
m4/1.4.18: checking for _set_invalid_parameter_handler... yes
m4/1.4.18: checking for fcntl... no
m4/1.4.18: checking for symlink... no
m4/1.4.18: checking for mempcpy... no
m4/1.4.18: checking for fpurge... no
m4/1.4.18: checking for __fpurge... no
m4/1.4.18: checking for __freadahead... no
m4/1.4.18: checking for __freading... no
m4/1.4.18: checking for getdtablesize... no
m4/1.4.18: checking for getprogname... no
m4/1.4.18: checking for getexecname... no
m4/1.4.18: checking for gettimeofday... no
m4/1.4.18: checking for lstat... no
m4/1.4.18: checking for mbsinit... no
m4/1.4.18: checking for mbrtowc... yes
m4/1.4.18: checking for mprotect... no
m4/1.4.18: checking for mkstemp... no
m4/1.4.18: checking for nl_langinfo... no
m4/1.4.18: checking for pipe2... no
m4/1.4.18: checking for isblank... yes
m4/1.4.18: checking for iswctype... yes
m4/1.4.18: checking for link... no
m4/1.4.18: checking for secure_getenv... no
m4/1.4.18: checking for getuid... no
m4/1.4.18: checking for geteuid... no
m4/1.4.18: checking for getgid... no
m4/1.4.18: checking for getegid... no
m4/1.4.18: checking for sigaction... no
m4/1.4.18: checking for siginterrupt... no
m4/1.4.18: checking for snprintf... no
m4/1.4.18: checking for strndup... no
m4/1.4.18: checking for pipe... no
m4/1.4.18: checking for vasnprintf... no
m4/1.4.18: checking for wcrtomb... yes
m4/1.4.18: checking for iswcntrl... yes
m4/1.4.18: checking for newlocale... no
m4/1.4.18: checking for setenv... no
m4/1.4.18: checking for sleep... no
m4/1.4.18: checking for strdup... yes
m4/1.4.18: checking for wctob... yes
m4/1.4.18: checking for nl_langinfo and CODESET... no
m4/1.4.18: checking for a traditional french locale... French_France.1252
m4/1.4.18: checking for ucontext.h... no
m4/1.4.18: checking for unistd.h... (cached) no
m4/1.4.18: checking for sys/param.h... no
m4/1.4.18: checking for sys/socket.h... no
m4/1.4.18: checking for stdio_ext.h... no
m4/1.4.18: checking for sys/stat.h... (cached) yes
m4/1.4.18: checking for getopt.h... no
m4/1.4.18: checking for sys/time.h... no
m4/1.4.18: checking for langinfo.h... no
m4/1.4.18: checking for limits.h... yes
m4/1.4.18: checking for xlocale.h... no
m4/1.4.18: checking for math.h... yes
m4/1.4.18: checking for sys/mman.h... no
m4/1.4.18: checking for malloc.h... yes
m4/1.4.18: checking for sys/cdefs.h... no
m4/1.4.18: checking for spawn.h... no
m4/1.4.18: checking for wchar.h... yes
m4/1.4.18: checking for stdint.h... (cached) yes
m4/1.4.18: checking for sys/wait.h... no
m4/1.4.18: checking for features.h... no
m4/1.4.18: checking for wctype.h... yes
m4/1.4.18: checking for dirent.h... no
m4/1.4.18: checking for inttypes.h... (cached) yes
m4/1.4.18: checking for working C stack overflow detection... no
m4/1.4.18: checking for non-GNU ld... link
m4/1.4.18: checking if the linker (link) is GNU ld... no
m4/1.4.18: checking for shared library run path origin... done
m4/1.4.18: checking for libsigsegv... no, consider installing GNU libsigsegv
m4/1.4.18: checking whether // is distinct from /... yes
m4/1.4.18: checking whether realpath works... no
m4/1.4.18: checking if environ is properly declared... yes
m4/1.4.18: checking whether the preprocessor supports include_next... no
m4/1.4.18: checking whether system header files limit the line length... no
m4/1.4.18: checking for complete errno.h... no
m4/1.4.18: checking absolute name of <errno.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\errno.h"
m4/1.4.18: checking for EMULTIHOP value... no
m4/1.4.18: checking for ENOLINK value... yes
m4/1.4.18: checking for EOVERFLOW value... yes
m4/1.4.18: checking whether strerror_r is declared... no
m4/1.4.18: checking for strerror_r... no
m4/1.4.18: checking whether strerror_r returns char *... no
m4/1.4.18: checking for mode_t... no
m4/1.4.18: checking for sig_atomic_t... yes
m4/1.4.18: checking for working fcntl.h... no
m4/1.4.18: checking for pid_t... no
m4/1.4.18: checking whether frexp() can be used without linking with libm... yes
m4/1.4.18: checking whether alarm is declared... no
m4/1.4.18: checking whether long double and double are the same... yes
m4/1.4.18: checking whether stdin defaults to large file offsets... yes
m4/1.4.18: checking for 64-bit off_t... no
m4/1.4.18: checking absolute name of <sys/types.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\sys/types.h"
m4/1.4.18: checking whether fseeko is declared... no
m4/1.4.18: checking for fseeko... no
m4/1.4.18: checking whether stat file-mode macros are broken... no
m4/1.4.18: checking absolute name of <sys/stat.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\sys/stat.h"
m4/1.4.18: checking for nlink_t... no
m4/1.4.18: checking whether ftello is declared... no
m4/1.4.18: checking for ftello... no
m4/1.4.18: checking whether getdtablesize is declared... no
m4/1.4.18: checking absolute name of <getopt.h>... <getopt.h>
m4/1.4.18: checking for getopt.h... (cached) no
m4/1.4.18: checking whether getenv is declared... yes
m4/1.4.18: checking for C/C++ restrict keyword... no
m4/1.4.18: checking absolute name of <sys/time.h>... <sys/time.h>
m4/1.4.18: checking winsock2.h usability... yes
m4/1.4.18: checking winsock2.h presence... yes
m4/1.4.18: checking for winsock2.h... yes
m4/1.4.18: checking for struct timeval... yes
m4/1.4.18: checking for wide-enough struct timeval.tv_sec member... no
m4/1.4.18: checking where to find the exponent in a 'double'... word 1 bit 20
m4/1.4.18: checking where to find the exponent in a 'float'... word 0 bit 23
m4/1.4.18: checking whether byte ordering is bigendian... no
m4/1.4.18: checking absolute name of <limits.h>... "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\include\\limits.h"
m4/1.4.18: checking whether limits.h has ULLONG_WIDTH etc.... no
m4/1.4.18: checking whether getc_unlocked is declared... no
m4/1.4.18: checking whether we are using the GNU C Library >= 2.1 or uClibc... no
m4/1.4.18: checking for wchar_t... yes
m4/1.4.18: checking for max_align_t... no
m4/1.4.18: checking whether NULL can be used in arbitrary expressions... yes
m4/1.4.18: checking absolute name of <stddef.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\stddef.h"
m4/1.4.18: checking for multithread API to use... none
m4/1.4.18: checking whether lstat correctly handles trailing slash... no
m4/1.4.18: checking for a sed that does not truncate output... /usr/bin/sed
m4/1.4.18: checking whether malloc, realloc, calloc are POSIX compliant... no
m4/1.4.18: checking for stdlib.h... (cached) yes
m4/1.4.18: checking for GNU libc compatible malloc... yes
m4/1.4.18: checking for mbstate_t... yes
m4/1.4.18: checking for a traditional japanese locale... none
m4/1.4.18: checking for a transitional chinese locale... none
m4/1.4.18: checking for a french Unicode locale... French_France.65001
m4/1.4.18: checking for mmap... no
m4/1.4.18: checking whether memchr works... yes
m4/1.4.18: checking whether <limits.h> defines MIN and MAX... no
m4/1.4.18: checking whether <sys/param.h> defines MIN and MAX... no
m4/1.4.18: checking for promoted mode_t type... mode_t
m4/1.4.18: checking for library containing posix_spawn... no
m4/1.4.18: checking for posix_spawn... no
m4/1.4.18: checking for sigset_t... no
m4/1.4.18: checking for SIGPIPE... no
m4/1.4.18: checking for inline... inline
m4/1.4.18: checking for uid_t in sys/types.h... no
m4/1.4.18: checking whether C symbols are prefixed with underscore at the linker level... yes
m4/1.4.18: checking whether snprintf returns a byte count as in C99... yes
m4/1.4.18: checking whether snprintf is declared... yes
m4/1.4.18: checking for stdbool.h that conforms to C99... yes
m4/1.4.18: checking for _Bool... yes
m4/1.4.18: checking for wint_t... yes
m4/1.4.18: checking whether wint_t is too small... yes
m4/1.4.18: checking absolute name of <stdint.h>... "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\include\\stdint.h"
m4/1.4.18: checking whether stdint.h conforms to C99... yes
m4/1.4.18: checking whether stdint.h predates C++11... no
m4/1.4.18: checking whether stdint.h has UINTMAX_WIDTH etc.... no
m4/1.4.18: checking whether strerror(0) succeeds... yes
m4/1.4.18: checking absolute name of <string.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\string.h"
m4/1.4.18: checking whether strndup is declared... no
m4/1.4.18: checking whether strnlen is declared... yes
m4/1.4.18: checking whether strsignal is declared... no
m4/1.4.18: checking whether sys_siglist is declared... no
m4/1.4.18: checking whether strstr works... yes
m4/1.4.18: checking whether ldexp() can be used without linking with libm... yes
m4/1.4.18: checking for struct timespec in <time.h>... yes
m4/1.4.18: checking absolute name of <time.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\time.h"
m4/1.4.18: checking whether clearerr_unlocked is declared... no
m4/1.4.18: checking whether feof_unlocked is declared... no
m4/1.4.18: checking whether ferror_unlocked is declared... no
m4/1.4.18: checking whether fflush_unlocked is declared... no
m4/1.4.18: checking whether fgets_unlocked is declared... no
m4/1.4.18: checking whether fputc_unlocked is declared... no
m4/1.4.18: checking whether fputs_unlocked is declared... no
m4/1.4.18: checking whether fread_unlocked is declared... no
m4/1.4.18: checking whether fwrite_unlocked is declared... no
m4/1.4.18: checking whether getchar_unlocked is declared... no
m4/1.4.18: checking whether putc_unlocked is declared... no
m4/1.4.18: checking whether putchar_unlocked is declared... no
m4/1.4.18: checking for inttypes.h... yes
m4/1.4.18: checking for stdint.h... yes
m4/1.4.18: checking for intmax_t... yes
m4/1.4.18: checking for snprintf... (cached) no
m4/1.4.18: checking for strnlen... yes
m4/1.4.18: checking for wcslen... yes
m4/1.4.18: checking for wcsnlen... yes
m4/1.4.18: checking for mbrtowc... (cached) yes
m4/1.4.18: checking for wcrtomb... (cached) yes
m4/1.4.18: checking whether _snprintf is declared... yes
m4/1.4.18: checking whether printf supports size specifiers as in C99... yes
m4/1.4.18: checking whether printf supports 'long double' arguments... yes
m4/1.4.18: checking whether printf supports infinite 'double' arguments... yes
m4/1.4.18: checking whether printf supports infinite 'long double' arguments... yes
m4/1.4.18: checking whether printf supports the 'a' and 'A' directives... no
m4/1.4.18: checking whether printf supports the 'F' directive... yes
m4/1.4.18: checking whether printf supports the 'n' directive... no
m4/1.4.18: checking whether printf supports the 'ls' directive... yes
m4/1.4.18: checking whether printf supports the grouping flag... no
m4/1.4.18: checking whether printf supports the left-adjust flag correctly... yes
m4/1.4.18: checking whether printf supports the zero flag correctly... yes
m4/1.4.18: checking whether printf supports large precisions... yes
m4/1.4.18: checking whether printf survives out-of-memory conditions... guessing no
m4/1.4.18: checking whether to use C++... no
m4/1.4.18: checking whether ungetc works on arbitrary bytes... yes
m4/1.4.18: checking whether getcwd (NULL, 0) allocates memory for result... yes
m4/1.4.18: checking for getcwd with POSIX signature... no
m4/1.4.18: checking absolute name of <inttypes.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\inttypes.h"
m4/1.4.18: checking for inttypes.h... (cached) yes
m4/1.4.18: checking whether the inttypes.h PRIxNN macros are broken... no
m4/1.4.18: checking for LC_MESSAGES... no
m4/1.4.18: checking for CFPreferencesCopyAppValue... no
m4/1.4.18: checking for CFLocaleCopyCurrent... no
m4/1.4.18: checking whether setenv is declared... no
m4/1.4.18: checking search.h usability... yes
m4/1.4.18: checking search.h presence... yes
m4/1.4.18: checking for search.h... yes
m4/1.4.18: checking for tsearch... no
m4/1.4.18: checking whether strdup is declared... yes
m4/1.4.18: checking whether unsetenv is declared... no
m4/1.4.18: checking whether to enable assertions... yes
m4/1.4.18: checking whether btowc(0) is correct... yes
m4/1.4.18: checking whether btowc(EOF) is correct... yes
m4/1.4.18: checking for __builtin_expect... no
m4/1.4.18: checking whether sigaltstack is declared... no
m4/1.4.18: checking for stack_t... no
m4/1.4.18: checking for winsock2.h... (cached) yes
m4/1.4.18: checking whether // is distinct from /... (cached) yes
m4/1.4.18: checking whether dup2 works... no
m4/1.4.18: checking for setdtablesize... no
m4/1.4.18: checking for error_at_line... no
m4/1.4.18: checking whether fflush works on input streams... no
m4/1.4.18: checking absolute name of <fcntl.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\fcntl.h"
m4/1.4.18: checking whether fflush works on input streams... (cached) no
m4/1.4.18: checking whether conversion from 'int' to 'long double' works... yes
m4/1.4.18: checking for __fpending... no
m4/1.4.18: checking whether fpurge is declared... no
m4/1.4.18: checking whether frexp works... yes
m4/1.4.18: checking whether frexpl is declared... yes
m4/1.4.18: checking whether frexpl() can be used without linking with libm... yes
m4/1.4.18: checking whether frexpl works... no
m4/1.4.18: checking for fseeko... (cached) no
m4/1.4.18: checking for _fseeki64... yes
m4/1.4.18: checking for ftello... (cached) no
m4/1.4.18: checking for _ftelli64... yes
m4/1.4.18: checking whether program_invocation_name is declared... no
m4/1.4.18: checking whether program_invocation_short_name is declared... no
m4/1.4.18: checking whether __argv is declared... yes
m4/1.4.18: checking sys/timeb.h usability... yes
m4/1.4.18: checking sys/timeb.h presence... yes
m4/1.4.18: checking for sys/timeb.h... yes
m4/1.4.18: checking for _ftime... yes
m4/1.4.18: checking whether isnan(double) can be used without linking with libm... yes
m4/1.4.18: checking whether isnan(float) can be used without linking with libm... yes
m4/1.4.18: checking whether isnan(float) works... no
m4/1.4.18: checking where to find the exponent in a 'float'... (cached) word 0 bit 23
m4/1.4.18: checking whether isnan(long double) can be used without linking with libm... yes
m4/1.4.18: checking whether isnanl works... no
m4/1.4.18: checking where to find the exponent in a 'long double'... word 1 bit 20
m4/1.4.18: checking absolute name of <langinfo.h>... <langinfo.h>
m4/1.4.18: checking for libsigsegv... (cached) no, consider installing GNU libsigsegv
m4/1.4.18: checking whether locale.h conforms to POSIX:2001... no
m4/1.4.18: checking whether struct lconv is properly defined... no
m4/1.4.18: checking absolute name of <locale.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\locale.h"
m4/1.4.18: checking for struct lconv.decimal_point... yes
m4/1.4.18: checking whether lseek detects pipes... no
m4/1.4.18: checking absolute name of <math.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\math.h"
m4/1.4.18: checking whether NAN macro works... yes
m4/1.4.18: checking whether HUGE_VAL works... yes
m4/1.4.18: checking whether mbsinit is declared... yes
m4/1.4.18: checking for mkdtemp... no
m4/1.4.18: checking for obstacks that work with any size object... no
m4/1.4.18: checking whether posix_spawn_file_actions_addclose works... no
m4/1.4.18: checking whether posix_spawn_file_actions_adddup2 works... no
m4/1.4.18: checking whether posix_spawn_file_actions_addopen works... no
m4/1.4.18: checking paths.h usability... no
m4/1.4.18: checking paths.h presence... no
m4/1.4.18: checking for paths.h... no
m4/1.4.18: checking for confstr... no
m4/1.4.18: checking for sched_setparam... no
m4/1.4.18: checking for sched_setscheduler... no
m4/1.4.18: checking for setegid... no
m4/1.4.18: checking for seteuid... no
m4/1.4.18: checking for vfork... no
m4/1.4.18: checking whether frexp works... (cached) yes
m4/1.4.18: checking whether ldexp can be used without linking with libm... (cached) yes
m4/1.4.18: checking whether frexpl() can be used without linking with libm... (cached) yes
m4/1.4.18: checking whether frexpl works... (cached) no
m4/1.4.18: checking whether ldexpl() can be used without linking with libm... yes
m4/1.4.18: checking whether ldexpl works... yes
m4/1.4.18: checking whether ldexpl is declared... yes
m4/1.4.18: checking whether program_invocation_name is declared... (cached) no
m4/1.4.18: checking whether program_invocation_short_name is declared... (cached) no
m4/1.4.18: checking for raise... yes
m4/1.4.18: checking for rawmemchr... no
m4/1.4.18: checking for working re_compile_pattern... no
m4/1.4.18: checking libintl.h usability... no
m4/1.4.18: checking libintl.h presence... no
m4/1.4.18: checking for libintl.h... no
m4/1.4.18: checking whether isblank is declared... yes
m4/1.4.18: checking whether rename honors trailing slash on destination... no
m4/1.4.18: checking whether rename honors trailing slash on source... yes
m4/1.4.18: checking whether rename manages hard links correctly... yes
m4/1.4.18: checking whether rename manages existing destinations correctly... no
m4/1.4.18: checking whether rmdir works... no
m4/1.4.18: checking for sched.h... no
m4/1.4.18: checking absolute name of <sched.h>... ""
m4/1.4.18: checking for struct sched_param... no
m4/1.4.18: checking for __secure_getenv... no
m4/1.4.18: checking for issetugid... no
m4/1.4.18: checking for siginfo_t... no
m4/1.4.18: checking absolute name of <signal.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\signal.h"
m4/1.4.18: checking for volatile sig_atomic_t... yes
m4/1.4.18: checking for sighandler_t... no
m4/1.4.18: checking for signbit macro... yes
m4/1.4.18: checking for signbit compiler built-ins... no
m4/1.4.18: checking for stdint.h... (cached) yes
m4/1.4.18: checking for SIZE_MAX... yes
m4/1.4.18: checking for snprintf... (cached) no
m4/1.4.18: checking absolute name of <spawn.h>... <spawn.h>
m4/1.4.18: checking for ssize_t... no
m4/1.4.18: checking whether stat handles trailing slashes on directories... yes
m4/1.4.18: checking whether stat handles trailing slashes on files... yes
m4/1.4.18: checking for va_copy... yes
m4/1.4.18: checking for max_align_t... (cached) no
m4/1.4.18: checking whether NULL can be used in arbitrary expressions... (cached) yes
m4/1.4.18: checking absolute name of <stddef.h>... (cached) "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\stddef.h"
m4/1.4.18: checking absolute name of <stdio.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\stdio.h"
m4/1.4.18: checking which flavor of printf attribute matches inttypes macros... system
m4/1.4.18: checking absolute name of <stdlib.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\stdlib.h"
m4/1.4.18: checking for strchrnul... no
m4/1.4.18: checking for winsock2.h... (cached) yes
m4/1.4.18: checking for working strnlen... yes
m4/1.4.18: checking for strsignal... no
m4/1.4.18: checking whether _sys_siglist is declared... no
m4/1.4.18: checking whether strstr works in linear time... no
m4/1.4.18: checking whether strstr works... (cached) yes
m4/1.4.18: checking whether strtod obeys C99... yes
m4/1.4.18: checking absolute name of <sys/stat.h>... (cached) "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\sys/stat.h"
m4/1.4.18: checking for nlink_t... (cached) no
m4/1.4.18: checking absolute name of <sys/wait.h>... <sys/wait.h>
m4/1.4.18: checking absolute name of <unistd.h>... <unistd.h>
m4/1.4.18: checking for ptrdiff_t... yes
m4/1.4.18: checking for vasprintf... no
m4/1.4.18: checking for vasprintf... (cached) no
m4/1.4.18: checking for nl_langinfo... (cached) no
m4/1.4.18: checking for ptrdiff_t... (cached) yes
m4/1.4.18: checking for waitid... no
m4/1.4.18: checking absolute name of <wchar.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\wchar.h"
m4/1.4.18: checking absolute name of <wctype.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\wctype.h"
m4/1.4.18: checking whether iswcntrl works... yes
m4/1.4.18: checking for towlower... yes
m4/1.4.18: checking for wctype_t... yes
m4/1.4.18: checking for wctrans_t... yes
m4/1.4.18: checking for stdint.h... (cached) yes
m4/1.4.18: checking for a traditional french locale... (cached) French_France.1252
m4/1.4.18: checking for a french Unicode locale... (cached) French_France.65001
m4/1.4.18: checking for a traditional french locale... (cached) French_France.1252
m4/1.4.18: checking for a turkish Unicode locale... none
m4/1.4.18: checking for closedir... no
m4/1.4.18: checking absolute name of <ctype.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt\\ctype.h"
m4/1.4.18: checking absolute name of <dirent.h>... <dirent.h>
m4/1.4.18: checking for dirfd... no
m4/1.4.18: checking whether dirfd is declared... no
m4/1.4.18: checking whether dirfd is a macro... no
m4/1.4.18: checking how to get the file descriptor associated with an open DIR*... no_such_member
m4/1.4.18: checking whether dup works... no
m4/1.4.18: checking for flexible array member... yes
m4/1.4.18: checking for getpagesize... no
m4/1.4.18: checking OS.h usability... no
m4/1.4.18: checking OS.h presence... no
m4/1.4.18: checking for OS.h... no
m4/1.4.18: checking for sys/param.h... (cached) no
m4/1.4.18: checking whether getpagesize is declared... no
m4/1.4.18: checking whether INT32_MAX < INTMAX_MAX... yes
m4/1.4.18: checking whether INT64_MAX == LONG_MAX... no
m4/1.4.18: checking whether UINT32_MAX < UINTMAX_MAX... yes
m4/1.4.18: checking whether UINT64_MAX == ULONG_MAX... no
m4/1.4.18: checking where to find the exponent in a 'double'... (cached) word 1 bit 20
m4/1.4.18: checking where to find the exponent in a 'float'... (cached) word 0 bit 23
m4/1.4.18: checking where to find the exponent in a 'long double'... (cached) word 1 bit 20
m4/1.4.18: checking for setlocale... yes
m4/1.4.18: checking for uselocale... no
m4/1.4.18: checking for a traditional french locale... (cached) French_France.1252
m4/1.4.18: checking for a french Unicode locale... (cached) French_France.65001
m4/1.4.18: checking for a traditional japanese locale... (cached) none
m4/1.4.18: checking for a transitional chinese locale... (cached) none
m4/1.4.18: checking for a french Unicode locale... (cached) French_France.65001
m4/1.4.18: checking for mmap... (cached) no
m4/1.4.18: checking for mmap... (cached) no
m4/1.4.18: checking for a traditional french locale... (cached) French_France.1252
m4/1.4.18: checking for a french Unicode locale... (cached) French_France.65001
m4/1.4.18: checking for opendir... no
m4/1.4.18: checking for putenv compatible with GNU and SVID... no
m4/1.4.18: checking whether _putenv is declared... yes
m4/1.4.18: checking for mmap... (cached) no
m4/1.4.18: checking for mmap... (cached) no
m4/1.4.18: checking for readdir... no
m4/1.4.18: checking for a traditional french locale... (cached) French_France.1252
m4/1.4.18: checking for a french Unicode locale... (cached) French_France.65001
m4/1.4.18: checking for a traditional japanese locale... (cached) none
m4/1.4.18: checking for a transitional chinese locale... (cached) none
m4/1.4.18: checking whether sleep is declared... no
m4/1.4.18: checking for working stdalign.h... no
m4/1.4.18: checking for mmap... (cached) no
m4/1.4.18: checking for mmap... (cached) no
m4/1.4.18: checking for unsetenv... no
m4/1.4.18: checking for a traditional french locale... (cached) French_France.1252
m4/1.4.18: checking for a french Unicode locale... (cached) French_France.65001
m4/1.4.18: checking for a traditional japanese locale... (cached) none
m4/1.4.18: checking for a transitional chinese locale... (cached) none
m4/1.4.18: checking whether wctob works... no
m4/1.4.18: checking whether an open file can be renamed... no
m4/1.4.18: checking if changeword is wanted... no
m4/1.4.18: checking which shell to use for syscmd... /bin/sh
m4/1.4.18: checking if malloc debugging is wanted... no
m4/1.4.18: checking that generated files are newer than configure... done
m4/1.4.18: configure: creating ./config.status
m4/1.4.18: config.status: creating Makefile
m4/1.4.18: config.status: creating doc/Makefile
m4/1.4.18: config.status: creating lib/Makefile
m4/1.4.18: config.status: creating src/Makefile
m4/1.4.18: config.status: creating tests/Makefile
m4/1.4.18: config.status: creating checks/Makefile
m4/1.4.18: config.status: creating examples/Makefile
m4/1.4.18: config.status: creating lib/config.h
m4/1.4.18: config.status: linking /c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/source_subfolder/GNUmakefile to GNUmakefile
m4/1.4.18: config.status: executing depfiles commands
m4/1.4.18: config.status: executing stamp-h commands
m4/1.4.18: run_in_windows_bash: "C:\Program Files\Git\usr\bin\bash.exe" --login -c ^"cd \^"/c/users/appveyor/.conan/data/m4/1.4.18/_/_/build/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3\^" ^&^& make -j2 ^"
m4/1.4.18: /usr/bin/bash: make: command not found
m4/1.4.18: 
m4/1.4.18: ERROR: Package 'b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3' build failed
m4/1.4.18: WARN: Build folder C:\Users\appveyor\.conan\data\m4\1.4.18\_\_\build\b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Python37\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Users\appveyor\.conan\data\m4\1.4.18\_\_\export\conanfile.py", line 82, in build
    autotools.make()
  File "C:\Python37\lib\site-packages\conans\client\build\autotools_environment.py", line 233, in make
    win_bash=self._win_bash, subsystem=self.subsystem)
  File "C:\Python37\lib\site-packages\conans\model\conan_file.py", line 287, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 127 while executing make -j2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "build.py", line 54, in <module>
    builder.run()
  File "C:\Python37\lib\site-packages\cpt\packager.py", line 594, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "C:\Python37\lib\site-packages\cpt\packager.py", line 687, in run_builds
    r.run()
  File "C:\Python37\lib\site-packages\cpt\runner.py", line 131, in run
    lockfile=self._lockfile)
  File "C:\Python37\lib\site-packages\conans\client\conan_api.py", line 94, in wrapper
    return f(api, *args, **kwargs)
  File "C:\Python37\lib\site-packages\conans\client\conan_api.py", line 376, in create
    test_build_folder, test_folder, conanfile_path, recorder=recorder)
  File "C:\Python37\lib\site-packages\conans\client\cmd\create.py", line 43, in create
    recorder=recorder)
  File "C:\Python37\lib\site-packages\conans\client\cmd\test.py", line 38, in install_build_and_test
    recorder=recorder)
  File "C:\Python37\lib\site-packages\conans\client\manager.py", line 77, in deps_install
    graph_info=graph_info)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 295, in install
    self._build(nodes_by_level, keep_build, root_node, graph_info, remotes, build_mode, update)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 423, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 481, in _handle_node_cache
    pref = self._build_package(node, output, keep_build, remotes)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 511, in _build_package
    pref = builder.build_package(node, keep_build, self._recorder, remotes)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 227, in build_package
    raise exc
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 215, in build_package
    self._build(conanfile, pref)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 143, in _build
    raise exc
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 135, in _build
    run_build_method(conanfile, self._hook_manager, reference=pref.ref, package_id=pref.id)
  File "C:\Python37\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python37\lib\site-packages\conans\errors.py", line 40, in conanfile_exception_formatter
    raise ConanExceptionInUserConanfileMethod(msg)
conans.errors.ConanExceptionInUserConanfileMethod: m4/1.4.18: Error in build() method, line 82
	autotools.make()
	ConanException: Error 127 while executing make -j2
Command exited with code 1
```

**Comment by madebr** [comment]
`m4` expects `make` to be available through `msys2`.
But I cannot see `msys2` in your build requirements.
What winbash are you using?

**Comment by madebr** [comment]
Also note that both `automake/1.16.1` and `automake/1.16.2` are in your build requirements.
These might clash.

**Comment by jmarrec** [comment]
My recipe declares `bison/3.5.3` and it all trickles down from there. If I use `bison_installer/3.3.2@bincrafters/stable` instead it works fine.

My recipe: https://github.com/NREL/conan-openstudio-ruby/blob/5f2c3353a5aa21e93b6568c3d7a45e3431001ab0/conanfile.py#L72-L128


my appveyor config file:

```
build: false

environment:
    PYTHON_HOME: "C:\\Python37"
    CONAN_VISUAL_RUNTIMES: MD,MDd   # Ignoring MT and MTd
    # CONAN_ARCHS: x86_64,   # Don't want to build for x86

    matrix:

        # Try a Release build on 32bit <=== THIS ONE FAILS
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86

        # We now can support MSVC 2019: build both Release and Debug, x64 only
        # This works under 1hr
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release,Debug
          CONAN_ARCHS: x86_64

        # 2017 is the target MSVC for now, so build Release and Debug, x64 only
        # I separate the release and debug because I'm hitting the 60 minute per build job Appveyor limit...
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
- python build.py
```

**Comment by madebr** [comment]
You're using bash from git.
See https://ci.appveyor.com/project/ci-commercialbuildings/conan-openstudio-ruby/builds/34345124/job/o4ga9pkt9d1j1ybr#L1224

@ericLemanissier Do you know why conan picks this msys2 over the msys2 CCI package?
```
if tools.os_info.is_windows and "CONAN_BASH_PATH" not in os.environ and \
        tools.os_info.detect_windows_subsystem() != "msys2":
    self.build_requires("m4/20190524
```
is used in `m4`.

**Comment by ericLemanissier** [comment]
`tools.os_info.detect_windows_subsystem()` invokes bash to identify what sub system it has. "C:\Program Files\Git\usr\bin\bash.exe" is proably a minimal msys2 distribution, which does not have make.
I can see the following options:
- @jmarrec removes "C:\Program Files\Git\usr\bin\" from PATH on appveyor
- @jmarrec adds `msys2/20190524` build_requires (using a profile or [CONAN_BUILD_REQUIRES env var](https://github.com/conan-io/conan-package-tools) for example)
- we patch CCI recipe for m4 to add `or not tools.which("make")` in the if you copied above

**Comment by jmarrec** [comment]
I added option 3 in: https://github.com/conan-io/conan-center-index/pull/2298/files#diff-c604d67e81141ce689c970d284592749R29-R32

In the meantime, I'll follow option two and see if it fixes it. Thanks both.

**Comment by jmarrec** [comment]
Option 2 seems to have done the trick (I added `CONAN_BUILD_REQUIRES: msys2/20190524` for my x86 appveyor), thanks a lot!


https://ci.appveyor.com/project/ci-commercialbuildings/conan-openstudio-ruby/builds/34347448/job/k3f7573oh2kq3onu

**Comment by jmarrec** [comment]
Geez, seems like bison has the same msvc name problem as m4:

```
bison/3.5.3: checking for grep that handles long lines and -e... /c/.conan/bc9a75/1/bin/usr/bin/grep
bison/3.5.3: checking for egrep... /c/.conan/bc9a75/1/bin/usr/bin/grep -E
bison/3.5.3: checking for ANSI C header files... yes
bison/3.5.3: checking for sys/types.h... yes
bison/3.5.3: checking for sys/stat.h... yes
bison/3.5.3: checking for stdlib.h... yes
bison/3.5.3: checking for string.h... yes
bison/3.5.3: checking for memory.h... yes
bison/3.5.3: checking for strings.h... no
bison/3.5.3: checking for inttypes.h... yes
bison/3.5.3: checking for stdint.h... yes
bison/3.5.3: checking for unistd.h... no
bison/3.5.3: checking minix/config.h usability... no
bison/3.5.3: checking minix/config.h presence... no
bison/3.5.3: checking for minix/config.h... no
bison/3.5.3: checking whether it is safe to define __EXTENSIONS__... yes
bison/3.5.3: checking whether _XOPEN_SOURCE should be defined... no
bison/3.5.3: checking for Minix Amsterdam compiler... no
bison/3.5.3: checking for i686-windows-msvc-ar... /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/ar-lib lib
bison/3.5.3: checking build system type... Invalid configuration `x86_64-windows-msvc': system `msvc' not recognized
bison/3.5.3: configure: error: /bin/sh /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/build-aux/config.sub x86_64-windows-msvc failed
```
