### ISSUE TITLE
[package] tesseract/4.1.1: Loop detected: 'lzma_sdk/9.20' requires 'msys2/20190524'

### ISSUE THREAD

**Issue by sinall** [conan-io/conan-center-index#2213]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **tesseract/4.1.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **VC++ 2019**
  * Docker image: 
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile debug:

[settings]
arch=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
os_build=Windows
arch_build=x86
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install . -if conaninfo/Debug --profile debug --build missing --no-imports

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
========================================
ConanInstall
========================================
Executing task: ConanInstall
Configuration:
[settings]
arch=x86
arch_build=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: Loop detected: 'lzma_sdk/9.20' requires 'msys2/20190524' which is an ancestor too
Exit code: 1
```

</details>

**Comment by uilianries** [comment]
Hi @sinall Please, take a look at https://github.com/conan-io/conan-center-index/issues/780 This problem is known, but it has been solved in the past. Regards!

**Comment by sinall** [comment]
@uilianries I know #780 , but the problem is still existing. Is it because some cache in my machine?

**Comment by sinall** [comment]
After `conan remove lzma_sdk`, it works now.

**Comment by uilianries** [comment]
@sinall Thanks for your feedback!
