### ISSUE TITLE
[package] qt/6.6.1: Version conflict between expat/2.5.0 and expat/2.6.0

### ISSUE THREAD

**Issue by stevenwdv** [conan-io/conan-center-index#22789]
### Description

There is a version conflict between qt/6.6.1 -> expat/2.6.0 and qt/6.6.1 -> wayland/1.22.0 -> expat 2.5.0.

I don't get how, because it seems to me that qt doesn't even require expat without qtwebengine, and even then it requires expat/2.5.0 ??

This even happens on a completely fresh Ubuntu install (via Docker).

### Package and Environment Details

* Package Name/Version: **qt/6.6.1**
* Operating System+version: **Linux**
* Compiler+version: N/A
* Docker image: N/A
* Conan version: **conan 2.1.0**
* Python version: **Python 3.10.12**

### Conan profile

```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
```

### Steps to reproduce

```shell
conan graph info --requires qt/6.6.1
```

### Logs

```
ERROR: Version conflict: Conflict between expat/2.5.0 and expat/2.6.0 in the graph.
Conflict originates from wayland/1.22.0
```

**Comment by ehargitt** [comment]
This also happens to me when building `qt/6.5.3` using Ubuntu 20.04 (Docker), Conan 2.1.0, and Python 3.10.5.
```
ERROR: Version conflict: Conflict between expat/2.5.0 and expat/2.6.0 in the graph.
Conflict originates from wayland/1.22.0
```

**Comment by andsfonseca** [comment]
The issue started occurring after the changes in #22727. A solution has already been proposed a in #22788.

**Comment by andsfonseca** [comment]
It appears that the issue has been resolved. Could you verify?

**Comment by stevenwdv** [comment]
@andsfonseca Yup it seems to work now :+1:

**Comment by ehargitt** [comment]
After clearing my cache and re-running my `conan create`, I'm still getting the same error, although it says conflict is from dbus:
```
ERROR: Version conflict: Conflict between expat/2.5.0 and expat/2.6.0 in the graph.
Conflict originates from dbus/1.15.8

Run conan graph info with your recipe and add --format=html to inspect the graph errors in an easier to visualize way.
```

Here is my create command:
```
conan create . --version 6.5.3 --profile:all gcc-9 -o:a qt5compat=True -o:a with_dbus=True --build=missing --format=json > create.json
```
