### ISSUE TITLE
In Android Studio, when installing ktx/4.3.2 using conan 2.14, an issue with zstd occurs.

### ISSUE THREAD

**Issue by longye-wwb** [conan-io/conan-center-index#27168]
### What is your question?

I have set up a conan 2.14 environment on my Android Studio, and I want to implement C++ functionality for processing ASTC and ETC2 textures using the ktx/4.3.2 library. However, when I configured my conanfile.txt file following the method provided on the official website (https://conan.io/center/recipes/ktx?version=4.3.2) and ran the BAT file for installation, I encountered the following issue:

It appears that the dependency zstd/1.5.5 of ktx/4.3.2 fails to compile:
```
C:\Users\asus\.conan2\p\b\zstdfaa0a2ecacf5a\b\src\lib\legacy\zstd_v04.c:3548:35: warning: a function declaration without
      a prototype is deprecated in all versions of C [-Wstrict-prototypes]
 3548 | size_t ZBUFFv04_recommendedDInSize()  { return BLOCKSIZE + 3; }
      |                                   ^
      |                                    void
C:\Users\asus\.conan2\p\b\zstdfaa0a2ecacf5a\b\src\lib\legacy\zstd_v04.c:3549:36: warning: a function declaration without
      a prototype is deprecated in all versions of C [-Wstrict-prototypes]
 3549 | size_t ZBUFFv04_recommendedDOutSize() { return BLOCKSIZE; }
      |                                    ^
      |                                     void
2 warnings generated.
[ 67%] Linking C static library libzstd.a
[ 67%] Built target libzstd_static
mingw32-make: *** [Makefile:135: all] Error 2

zstd/1.5.5: ERROR:
Package '8d05c26c39ba2bf5ef2c5548725c8c5306343016' build failed
zstd/1.5.5: WARN: Build folder C:\Users\asus\.conan2\p\b\zstdfaa0a2ecacf5a\b\build\Debug
ERROR: zstd/1.5.5: Error in build() method, line 69
        cmake.build()
        ConanException: Error 2 while executing
```
My conanfile.txt is as follows:

```
[requires]
glm/1.0.1
libwebp/1.5.0
jsoncpp/1.9.6
astc-codec/cci.20190617
ktx/4.3.2

[generators]
CMakeDeps
CMakeToolchain

[layout]
cmake_layout
```
And my BAT file is as follows:
```
cls
for %%f in (armv7 armv8 x86_64 x86) do (
    conan install . -pr:h=android -s build_type=Debug -s arch=%%f --build=missing -c tools.cmake.cmake_layout:build_folder_vars=['settings.arch']
    conan install . -pr:h=android -s build_type=Release -s arch=%%f --build=missing -c tools.cmake.cmake_layout:build_folder_vars=['settings.arch']
)
pause
```
Please help me, I can't find a way to solve this problem.

**Comment by AbrilRBS** [comment]
Hi @longye-wwb thanks for taking the time to report this issue

Could you please share the contents of your `android` profile?
This way we can more easily check what might be going wrong on your case, we have some usual suspects based on your provided error, but we can't known for sure without it :)

Thanks!

**Comment by longye-wwb** [comment]
> Hi [@longye-wwb](https://github.com/longye-wwb) thanks for taking the time to report this issue
> 
> Could you please share the contents of your `android` profile? This way we can more easily check what might be going wrong on your case, we have some usual suspects based on your provided error, but we can't known for sure without it :)
> 
> Thanks!

Thank you for taking the time to look into my issue，I'm not quite sure which files you're referring to, but I'll list a few of my own guesses below.

This is my .conan2/profiles/android file:
include(default)

[settings]
os=Android
os.api_level=30
compiler=clang
compiler.version=17
compiler.libcxx=c++_static
compiler.cppstd=17

[conf]
tools.android:ndk_path=C:\Users\asus\AppData\Local\Android\Sdk\ndk\27.0.12077973\
tools.cmake.cmaketoolchain:generator=MinGW Makefiles

This is my build.gradle.kts file:

plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace = "com.hive.mylibrary"
    compileSdk = 34

    defaultConfig {
        minSdk = 30

        ndk {
            abiFilters.add("x86_64")
            abiFilters.add("arm64-v8a")
        }

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
        externalNativeBuild {
            cmake {
                cppFlags += "-std=c++20"
                arguments("-DCMAKE_TOOLCHAIN_FILE=conan_android_toolchain.cmake")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }
}

dependencies {
    implementation(libs.appcompat)
    implementation(libs.material)
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}

**Comment by longye-wwb** [comment]
> Greetings,  问候，
> 
> I have a windows virtual machine. I'm trying to reproduce your issue but I'm founding other problems.我有一个 Windows 虚拟机。我尝试重现您的问题，但发现了其他问题。 Could you please specify step by step how to reproduce your build?您能否逐步说明如何重现您的构建？
> 
> Which is your environment?您的环境是哪种？
> 
> Thank you!  谢谢你！

Thank you for taking the time to reproduce my issue.
I am using the latest Android Studio with its GameActivity framework, writing code using CMake + NDK. My Gradle version is gradle-8.9-bin.zip, CMake version is "3.22.1", Android SDK corresponds to minSdk = 30, targetSdk = 34, and C++ version is 17. I configured Conan 2.14 in the project following the official Conan website's method, integrating third-party libraries via conanfile.txt and conan_android_toolchain.cmake, and declaring these in the CMakeLists.txt file:
conanfile.txt:
[requires]
glm/1.0.1
libwebp/1.5.0
jsoncpp/1.9.6
astc-codec/cci.20190617

[generators]
CMakeDeps
CMakeToolchain

[layout]
cmake_layout

conan_android_toolchain.cmake​​:
if (NOT ANDROID_ABI OR NOT CMAKE_BUILD_TYPE)
    return()
endif()

if(${ANDROID_ABI} STREQUAL "x86_64")
    include("${CMAKE_CURRENT_LIST_DIR}/build/x86_64/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
elseif(${ANDROID_ABI} STREQUAL "x86")
    include("${CMAKE_CURRENT_LIST_DIR}/build/x86/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
elseif(${ANDROID_ABI} STREQUAL "arm64-v8a")
    include("${CMAKE_CURRENT_LIST_DIR}/build/armv8/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
elseif(${ANDROID_ABI} STREQUAL "armeabi-v7a")
    include("${CMAKE_CURRENT_LIST_DIR}/build/armv7/${CMAKE_BUILD_TYPE}/generators/conan_toolchain.cmake")
else()
    message(FATAL "Not supported configuration")
endif()


Currently, I have linked the KTX library via local download. Here is my CMake file:

​​CMakeLists.txt​​:
cmake_minimum_required(VERSION 3.22.1)

project("hivefxso")

########################## Set C++ 20 Start ################################
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
########################## Set C++ 20 End ################################

########################## Third-party Library Configurations Start ##########################

# OpenCV
include_directories(${CMAKE_SOURCE_DIR}/opencv-mobile/sdk/native/jni/include)
set(OpenCV_DIR "${CMAKE_SOURCE_DIR}/opencv-mobile/sdk/native/jni")

# KTX Path Settings
if(CMAKE_ANDROID_ARCH_ABI STREQUAL "arm64-v8a")
    set(KTX_LIB_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/arm64-v8a/lib)
    set(KTX_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/arm64-v8a/include)
elseif(CMAKE_ANDROID_ARCH_ABI STREQUAL "x86_64")
    set(KTX_LIB_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/x86_64/lib)
    set(KTX_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/x86_64/include)
else()
    message(FATAL_ERROR "Unsupported ABI: ${CMAKE_ANDROID_ARCH_ABI}")
endif()

include_directories(${KTX_INCLUDE_PATH})

# Import KTX Shared Library
add_library(ktx SHARED IMPORTED)
set_target_properties(ktx PROPERTIES IMPORTED_LOCATION ${KTX_LIB_PATH}/libktx.so)

########################## Third-party Library Configurations End ##########################

add_library(${CMAKE_PROJECT_NAME} SHARED
        SlideWindow.cpp
        SingleTexturePlayer.cpp
        SequenceFramePlayer.cpp
        BillBoardManager.cpp
        AsyncSequenceFramePlayer.cpp
        ShaderProgram.cpp
        ScreenQuad.cpp
        Texture2D.cpp
        JsonReader.cpp
        EnumReflect.cpp
        SnowStylizer.cpp
        TextureBlender.cpp
        BlendManager.cpp
        TimeUtils.cpp
        AppContext.cpp
        FileUtils.cpp
        ThreadPool.cpp
)

set(REQUIRED_PACKAGES
        glm
        WebP
        jsoncpp
        OpenCV
        astc-codec
)

foreach(PACKAGE ${REQUIRED_PACKAGES})
    find_package(${PACKAGE} REQUIRED)
endforeach()

target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ${OpenCV_INCLUDE_DIRS})

target_link_libraries(${CMAKE_PROJECT_NAME}
        android
        log
        EGL
        GLESv3
        glm::glm
        libwebp::libwebp
        JsonCpp::JsonCpp
        ${OpenCV_LIBS}
        astc-codec::astc-codec
        ktx
)

# Set Library Output Directory
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/../jniLibs/${CMAKE_ANDROID_ARCH_ABI})
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES
        LIBRARY_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})

**Comment by longye-wwb** [comment]
> Thank you for your quick response.感谢您的快速回复。 I have formatted a little bit your comment as it was difficult to read by surrounding the code block with "```"我对您的评论进行了一些格式化，因为用“```”括住代码块会使阅读变得困难。
> 
> I suggest breaking the problem into smaller and easy-to-reproduce parts.我建议将问题分解为更小且易于重现的部分。
> 
> 1. Write a basic profile, in my case (I'm on a MacOS M3 machine):就我的情况而言（我在 MacOS M3 机器上），编写一个基本配置文件：
>    profile:  轮廓：
> 
> ```
> [settings]
> os=Android
> arch=armv8
> build_type=Release
> os.api_level=30
> compiler=clang
> compiler.version=17
> compiler.libcxx=c++_static
> compiler.cppstd=17
> 
> [conf]
> tools.android:ndk_path=/opt/homebrew/share/android-ndk
> ```
> 
> 2. Check if installing the dependencies works well in your system:检查在您的系统中安装依赖项是否正常：
> 
> $ conan install . --profile:host profile
> This should generate the following files:这应该会生成以下文件：
> 
> $ tree build                                                                             
> build
> └── Release
>     └── generators
>         ├── CMakePresets.json
>         ├── WebP-Target-release.cmake
>         ├── WebP-release-armv8-data.cmake
>         ├── WebPConfig.cmake
>         ├── WebPConfigVersion.cmake
>         ├── WebPTargets.cmake
>         ├── astc-codec-Target-release.cmake
>         ├── astc-codec-config-version.cmake
>         ├── astc-codec-config.cmake
>         ├── astc-codec-release-armv8-data.cmake
>         ├── astc-codecTargets.cmake
>         ├── cmakedeps_macros.cmake
>         ├── conan_toolchain.cmake
>         ├── conanbuild.sh
>         ├── conanbuildenv-release-armv8.sh
>         ├── conandeps_legacy.cmake
>         ├── conanrun.sh
>         ├── conanrunenv-release-armv8.sh
>         ├── deactivate_conanbuild.sh
>         ├── deactivate_conanrun.sh
>         ├── glm-Target-release.cmake
>         ├── glm-config-version.cmake
>         ├── glm-config.cmake
>         ├── glm-release-armv8-data.cmake
>         ├── glmTargets.cmake
>         ├── jsoncpp-Target-release.cmake
>         ├── jsoncpp-config-version.cmake
>         ├── jsoncpp-config.cmake
>         ├── jsoncpp-release-armv8-data.cmake
>         └── jsoncppTargets.cmake
> 
> 3 directories, 30 files
> If `zsstd` dependency is failing to compile, it should have failed.如果 `zsstd` 依赖项无法编译，那么它应该已经失败。 Append the proper traces if so!如果是的话，请附加适当的痕迹！

"I appreciate your help. Following your instructions, I successfully generated all these files in my build/generators directory, and zstd files were properly included among them.

    astc-codec-config-version.cmake
    astc-codec-config.cmake
    astc-codec-release-x86_64-data.cmake
    astc-codec-Target-release.cmake
    astc-codecTargets.cmake
    cmakedeps_macros.cmake
    CMakePresets.json
    conanbuild.bat
    conanbuildenv-release-x86_64.bat
    conandeps_legacy.cmake
    conanrun.bat
    conanrunenv-release-x86_64.bat
    conan_toolchain.cmake
    deactivate_conanbuild.bat
    deactivate_conanrun.bat
    glm-config-version.cmake
    glm-config.cmake
    glm-release-x86_64-data.cmake
    glm-Target-release.cmake
    glmTargets.cmake
    jsoncpp-config-version.cmake
    jsoncpp-config.cmake
    jsoncpp-release-x86_64-data.cmake
    jsoncpp-Target-release.cmake
    jsoncppTargets.cmake
    Ktx-release-x86_64-data.cmake
    Ktx-Target-release.cmake
    KtxConfig.cmake
    KtxConfigVersion.cmake
    KtxTargets.cmake
    WebP-release-x86_64-data.cmake
    WebP-Target-release.cmake
    WebPConfig.cmake
    WebPConfigVersion.cmake
    WebPTargets.cmake
    zstd-config-version.cmake
    zstd-config.cmake
    zstd-release-x86_64-data.cmake
    zstd-Target-release.cmake
    zstdTargets.cmake

**Comment by longye-wwb** [comment]
> Thank you for your quick response. I have formatted a little bit your comment as it was difficult to read by surrounding the code block with "```"
> 
> I suggest breaking the problem into smaller and easy-to-reproduce parts.
> 
> 1. Write a basic profile, in my case (I'm on a MacOS M3 machine):
>    profile:
> 
> ```
> [settings]
> os=Android
> arch=armv8
> build_type=Release
> os.api_level=30
> compiler=clang
> compiler.version=17
> compiler.libcxx=c++_static
> compiler.cppstd=17
> 
> [conf]
> tools.android:ndk_path=/opt/homebrew/share/android-ndk
> ```
> 
> 2. Check if installing the dependencies works well in your system:
> 
> $ conan install . --profile:host profile
> This should generate the following files:
> 
> $ tree build                                                                             
> build
> └── Release
>     └── generators
>         ├── CMakePresets.json
>         ├── WebP-Target-release.cmake
>         ├── WebP-release-armv8-data.cmake
>         ├── WebPConfig.cmake
>         ├── WebPConfigVersion.cmake
>         ├── WebPTargets.cmake
>         ├── astc-codec-Target-release.cmake
>         ├── astc-codec-config-version.cmake
>         ├── astc-codec-config.cmake
>         ├── astc-codec-release-armv8-data.cmake
>         ├── astc-codecTargets.cmake
>         ├── cmakedeps_macros.cmake
>         ├── conan_toolchain.cmake
>         ├── conanbuild.sh
>         ├── conanbuildenv-release-armv8.sh
>         ├── conandeps_legacy.cmake
>         ├── conanrun.sh
>         ├── conanrunenv-release-armv8.sh
>         ├── deactivate_conanbuild.sh
>         ├── deactivate_conanrun.sh
>         ├── glm-Target-release.cmake
>         ├── glm-config-version.cmake
>         ├── glm-config.cmake
>         ├── glm-release-armv8-data.cmake
>         ├── glmTargets.cmake
>         ├── jsoncpp-Target-release.cmake
>         ├── jsoncpp-config-version.cmake
>         ├── jsoncpp-config.cmake
>         ├── jsoncpp-release-armv8-data.cmake
>         └── jsoncppTargets.cmake
> 
> 3 directories, 30 files
> If `zsstd` dependency is failing to compile, it should have failed. Append the proper traces if so!

"I appreciate your help. Following your instructions, I successfully generated all these files in my build/generators directory, and zstd files were properly included among them.
 astc-codec-config-version.cmake
    astc-codec-config.cmake
    astc-codec-release-x86_64-data.cmake
    astc-codec-Target-release.cmake
    astc-codecTargets.cmake
    cmakedeps_macros.cmake
    CMakePresets.json
    conanbuild.bat
    conanbuildenv-release-x86_64.bat
    conandeps_legacy.cmake
    conanrun.bat
    conanrunenv-release-x86_64.bat
    conan_toolchain.cmake
    deactivate_conanbuild.bat
    deactivate_conanrun.bat
    glm-config-version.cmake
    glm-config.cmake
    glm-release-x86_64-data.cmake
    glm-Target-release.cmake
    glmTargets.cmake
    jsoncpp-config-version.cmake
    jsoncpp-config.cmake
    jsoncpp-release-x86_64-data.cmake
    jsoncpp-Target-release.cmake
    jsoncppTargets.cmake
    Ktx-release-x86_64-data.cmake
    Ktx-Target-release.cmake
    KtxConfig.cmake
    KtxConfigVersion.cmake
    KtxTargets.cmake
    WebP-release-x86_64-data.cmake
    WebP-Target-release.cmake
    WebPConfig.cmake
    WebPConfigVersion.cmake
    WebPTargets.cmake
    zstd-config-version.cmake
    zstd-config.cmake
    zstd-release-x86_64-data.cmake
    zstd-Target-release.cmake
    zstdTargets.cmake

**Comment by Nekto89** [comment]
It was fixed in https://github.com/facebook/zstd/commit/43118da8a7fb51e660bfa7e958639c5cc8285580#diff-40c894060cf6002ed54d0349cc214c64e4fa82b7d523b8c6960317e520e62928 (zstd 1.5.6)

**Comment by Nekto89** [comment]
> > It was fixed in [facebook/zstd@43118da#diff-40c894060cf6002ed54d0349cc214c64e4fa82b7d523b8c6960317e520e62928](https://github.com/facebook/zstd/commit/43118da8a7fb51e660bfa7e958639c5cc8285580#diff-40c894060cf6002ed54d0349cc214c64e4fa82b7d523b8c6960317e520e62928) (zstd 1.5.6)
> 
> Thank you so much! Indeed, zstd/1.5.6 fixed this issue. However, doesn't conan's ktx/4.4.3 specifically require zstd 1.5.5? How should I modify the configuration to make it use zstd/1.5.6 instead?

From log I thought that the issue was caused by warning but it doesn't look like it's treated as error so the reason is something else.

**Comment by perseoGI** [comment]
> However, doesn't conan's ktx/4.4.3 specifically require zstd 1.5.5? How should I modify the configuration to make it use zstd/1.5.6 instead?

The ideal way of replacing a dependency requirement is to add the following section into your **profile** (not the conanfile.txt):

```
[replace_requires]
zstd/*: zstd/1.5.6
```

**Comment by longye-wwb** [comment]
> > However, doesn't conan's ktx/4.4.3 specifically require zstd 1.5.5? How should I modify the configuration to make it use zstd/1.5.6 instead?但是，conan 的 ktx/4.4.3 不是特别需要 zstd 1.5.5 吗？我应该如何修改配置以使其改用 zstd/1.5.6？
> 
> The ideal way of replacing a dependency requirement is to add the following section into your **profile** (not the conanfile.txt):替换依赖项要求的理想方法是将以下部分添加到您的**配置文件**中（而不是 conanfile.txt）：
> 
> ```
> [replace_requires]
> zstd/*: zstd/1.5.6
> ```
I really appreciate your assistance. You were absolutely right - even after referencing zstd 1.5.6, I was still encountering this issue. For now, I've resolved it by downloading and deploying the library locally, and it's now working properly in my project.

[ 66%] Linking C static library libzstd.a
[ 66%] Built target libzstd_static
mingw32-make: *** [Makefile:135: all] Error 2

zstd/1.5.6: ERROR:
Package '5acb91d4d59fb9a66d0a5e44ed894c34e1f33273' build failed
zstd/1.5.6: WARN: Build folder C:\Users\asus\.conan2\p\b\zstd3b35ff60a9aac\b\build\Release
ERROR: zstd/1.5.6: Error in build() method, line 72
        cmake.build()
        ConanException: Error 2 while executing

**Comment by longye-wwb** [comment]
> > However, doesn't conan's ktx/4.4.3 specifically require zstd 1.5.5? How should I modify the configuration to make it use zstd/1.5.6 instead?
> 
> The ideal way of replacing a dependency requirement is to add the following section into your **profile** (not the conanfile.txt):
> 
> ```
> [replace_requires]
> zstd/*: zstd/1.5.6
> ```

I really appreciate your assistance. You were absolutely right - even after referencing zstd 1.5.6, I was still encountering this issue. For now, I've resolved it by downloading and deploying the library locally, and it's now working properly in my project.

[ 66%] Linking C static library libzstd.a
[ 66%] Built target libzstd_static
mingw32-make: *** [Makefile:135: all] Error 2

zstd/1.5.6: ERROR:
Package '5acb91d4d59fb9a66d0a5e44ed894c34e1f33273' build failed
zstd/1.5.6: WARN: Build folder C:\Users\asus\.conan2\p\b\zstd3b35ff60a9aac\b\build\Release
ERROR: zstd/1.5.6: Error in build() method, line 72
        cmake.build()
        ConanException: Error 2 while executing

**Comment by perseoGI** [comment]
Greetings @longye-wwb,

So is the issue already resolved with conan?
Which is the exact build error when using the updated package with conan?
Which version have you manually download and is working good on your system?

**Comment by longye-wwb** [comment]
> Greetings [@longye-wwb](https://github.com/longye-wwb),
> 
> So is the issue already resolved with conan? Which is the exact build error when using the updated package with conan? Which version have you manually download and is working good on your system?

Apologies for the delayed response. My issue remains unresolved.

Initially, I attempted to integrate the KTX library via conan.io's official package manager, but encountered persistent zstd-related errors that prevented successful implementation.

As an alternative solution, I Downloaded the precompiled Android binaries (KTX-Software-4.4.0-Android.zip) directly from:
https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.4.0，then Implemented local integration using the following CMake configuration:
# KTX path configuration
if(CMAKE_ANDROID_ARCH_ABI STREQUAL "arm64-v8a")
    set(KTX_LIB_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/arm64-v8a/lib)
    set(KTX_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/arm64-v8a/include)
elseif(CMAKE_ANDROID_ARCH_ABI STREQUAL "x86_64")
    set(KTX_LIB_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/x86_64/lib)
    set(KTX_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/KTX-4.4.0/x86_64/include)
else()
    message(FATAL_ERROR "Unsupported ABI: ${CMAKE_ANDROID_ARCH_ABI}")
endif()

include_directories(${KTX_INCLUDE_PATH})

# Import KTX shared library
add_library(ktx SHARED IMPORTED)
set_target_properties(ktx PROPERTIES IMPORTED_LOCATION ${KTX_LIB_PATH}/libktx.so)

target_link_libraries(${CMAKE_PROJECT_NAME}
        android
        log
        EGL
        GLESv3
        glm::glm
        libwebp::libwebp
        JsonCpp::JsonCpp
        ${OpenCV_LIBS}
        astc-codec::astc-codec
        ktx
)
This local integration approach has successfully enabled KTX functionality in my project, though I'm still interested in resolving the original conan/zstd compatibility issue for future maintenance.

**Comment by Nekto89** [comment]
> [ 66%] Linking C static library libzstd.a
> [ 66%] Built target libzstd_static
> mingw32-make: *** [Makefile:135: all] Error 2

Can you provide full log? It should contain some additional errors.

**Comment by longye-wwb** [comment]
> > [ 66%] Linking C static library libzstd.a
> > [ 66%] Built target libzstd_static
> > mingw32-make: *** [Makefile:135: all] Error 2
> 
> Can you provide full log? It should contain some additional errors.

zstd/1.5.5: Running CMake.build()
zstd/1.5.5: RUN: cmake --build "C:\Users\asus\.conan2\p\b\zstdc6811b2dd97ba\b\build\Debug" -- -j32
[  1%] Copying manpage zstdless.1
[  3%] Copying manpage zstd.1
[  4%] Copying manpage zstdgrep.1
[  6%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/debug.c.o
[  8%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/entropy_common.c.o
[  9%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/error_private.c.o
[ 11%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/fse_decompress.c.o
[ 12%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/pool.c.o
[ 14%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/threading.c.o
[ 14%] Built target zstdgrep.1
[ 14%] Built target zstdless.1
[ 14%] Built target zstd.1
[ 16%] Creating unzstd.1 symlink
[ 17%] Creating zstdcat.1 symlink
CMake Error: failed to create symbolic link 'zstdcat.1': �ͻ���û���������Ȩ��
CMake Error: failed to create symbolic link 'unzstd.1': �ͻ���û���������Ȩ��


mingw32-make[2]: *** [programs\CMakeFiles\unzstd.1.dir\build.make:70: programs/CMakeFiles/unzstd.1] Error 1
mingw32-make[2]: *** [programs\CMakeFiles\zstdcat.1.dir\build.make:70: programs/CMakeFiles/zstdcat.1] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:467: programs/CMakeFiles/unzstd.1.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
mingw32-make[1]: *** [CMakeFiles\Makefile2:436: programs/CMakeFiles/zstdcat.1.dir/all] Error 2
[ 19%] [ 20%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/xxhash.c.oBuilding C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/common/zstd_common.c.o

[ 22%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/fse_compress.c.o
[ 24%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/hist.c.o
[ 25%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/huf_compress.c.o
[ 27%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_compress.c.o
[ 29%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_compress_sequences.c.o
[ 30%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_compress_literals.c.o
[ 32%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_compress_superblock.c.o
[ 33%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_double_fast.c.o
[ 35%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_fast.c.o
[ 37%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_lazy.c.o
[ 38%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_ldm.c.o
[ 40%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstd_opt.c.o
[ 41%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/compress/zstdmt_compress.c.o
[ 43%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/decompress/huf_decompress.c.o
[ 45%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/decompress/zstd_ddict.c.o
[ 46%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/decompress/zstd_decompress.c.o
[ 48%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/decompress/zstd_decompress_block.c.o
[ 50%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/dictBuilder/cover.c.o
[ 51%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/dictBuilder/divsufsort.c.o
[ 53%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/dictBuilder/fastcover.c.o
[ 54%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/dictBuilder/zdict.c.o
[ 56%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/legacy/zstd_v01.c.o
[ 58%] [ 59%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/legacy/zstd_v02.c.oBuilding C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/legacy/zstd_v03.c.o

[ 62%] [ 62%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/legacy/zstd_v04.c.oBuilding C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/legacy/zstd_v05.c.o

[ 64%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/legacy/zstd_v06.c.o
[ 66%] Building C object lib/CMakeFiles/libzstd_static.dir/C_/Users/asus/.conan2/p/b/zstdc6811b2dd97ba/b/src/lib/legacy/zstd_v07.c.o
C:\Users\asus\.conan2\p\b\zstdc6811b2dd97ba\b\src\lib\legacy\zstd_v04.c:3548:35: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
 3548 | size_t ZBUFFv04_recommendedDInSize()  { return BLOCKSIZE + 3; }
      |                                   ^
      |                                    void
C:\Users\asus\.conan2\p\b\zstdc6811b2dd97ba\b\src\lib\legacy\zstd_v04.c:3549:36: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
 3549 | size_t ZBUFFv04_recommendedDOutSize() { return BLOCKSIZE; }
      |                                    ^
      |                                     void
2 warnings generated.
[ 67%] Linking C static library libzstd.a
[ 67%] Built target libzstd_static
mingw32-make: *** [Makefile:135: all] Error 2

zstd/1.5.5: ERROR:
Package '8d05c26c39ba2bf5ef2c5548725c8c5306343016' build failed
zstd/1.5.5: WARN: Build folder C:\Users\asus\.conan2\p\b\zstdc6811b2dd97ba\b\build\Debug
ERROR: zstd/1.5.5: Error in build() method, line 69
        cmake.build()
        ConanException: Error 2 while executing

**Comment by Nekto89** [comment]
>  CMake Error: failed to create symbolic link 'zstdcat.1': �ͻ���û���������Ȩ��
>  CMake Error: failed to create symbolic link 'unzstd.1': �ͻ���û���������Ȩ��

Can you try with zstd/*:build_programs=False ?

**Comment by longye-wwb** [comment]
> > CMake Error: failed to create symbolic link 'zstdcat.1': �ͻ���û���������Ȩ��
> > CMake Error: failed to create symbolic link 'unzstd.1': �ͻ���û���������Ȩ��
> 
> Can you try with zstd/*:build_programs=False ?
> 
> Creation of symlinks might require Developer mode on Windows

Thank you for your response.I followed your instructions, but encountered a new issue.Here are my logs.
-- Conan: Component target declared 'zstd::libzstd_static'
-- Conan: Target declared 'zstd::libzstd'
-- Warning: Standard CMAKE_CXX_STANDARD value defined in conan_toolchain.cmake to 17 has been modified to 14 by C:/Users/asus/.conan2/p/b/ktx74fa4444ddabd/b/src/lib/astc-encoder/CMakeLists.txt
--   AVX2 backend     - OFF
--   SSE4.1 backend   - OFF
--   SSE2 backend     - OFF
--   NEON backend     - OFF
--   NONE backend     - ON
--   NATIVE backend   - OFF
--   Invariance       - ON
--   Shared libs      - OFF
--   Decompressor     - OFF
--   Diagnostics      - OFF
--   ASAN             - OFF
--   Unit tests       - OFF
-- Configuring done (1.3s)
-- Generating done (0.2s)
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_SH


-- Build files have been written to: C:/Users/asus/.conan2/p/b/ktx74fa4444ddabd/b/build/Release

ktx/4.3.2: Running CMake.build()
ktx/4.3.2: RUN: cmake --build "C:\Users\asus\.conan2\p\b\ktx74fa4444ddabd\b\build\Release" -- -j32
[  1%] [  1%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_averages_and_directions.cpp.o
Generate C:/Users/asus/.conan2/p/b/ktx74fa4444ddabd/b/src/lib/version.h
[  2%] Building CXX object CMakeFiles/ktx_read.dir/lib/basis_transcode.cpp.o[  3%]
Building CXX object CMakeFiles/ktx_read.dir/lib/miniz_wrapper.cpp.o
[  4%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_block_sizes.cpp.o
[  5%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_color_quantize.cpp.o
[  6%] Building CXX object CMakeFiles/objUtil.dir/utils/argparser.cpp.o
[  8%] [  8%] Building CXX object CMakeFiles/ktx_read.dir/lib/basisu/transcoder/basisu_transcoder.cpp.oBuilding CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_color_unquantize.cpp.o

[  9%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_compress_symbolic.cpp.o
[ 10%] Building C object CMakeFiles/ktx_read.dir/lib/checkheader.c.o
[ 12%] [ 12%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_compute_variance.cpp.oBuilding C object CMakeFiles/ktx_read.dir/lib/dfdutils/createdfd.c.o

[ 13%] Building C object CMakeFiles/ktx_read.dir/lib/dfdutils/colourspaces.c.o
[ 14%] Building C object CMakeFiles/ktx_read.dir/lib/dfdutils/interpretdfd.c.o
[ 15%] Building C object CMakeFiles/ktx_read.dir/lib/dfdutils/printdfd.c.o
[ 16%] Building CXX object interface/basisu_c_binding/CMakeFiles/obj_basisu_cbind.dir/src/basisu_c_binding.cpp.o
[ 17%] Building C object CMakeFiles/ktx_read.dir/lib/dfdutils/queries.c.o
[ 18%] Building C object CMakeFiles/ktx_read.dir/lib/dfdutils/vk2dfd.c.o
[ 19%] Building CXX object CMakeFiles/ktx_read.dir/lib/etcdec.cxx.o
[ 20%] Building CXX object CMakeFiles/ktx_read.dir/lib/etcunpack.cxx.o
[ 22%] [ 22%] Building C object CMakeFiles/ktx_read.dir/lib/filestream.c.o
Building C object CMakeFiles/ktx_read.dir/lib/hashlist.c.o
[ 23%] Building C object CMakeFiles/ktx_read.dir/lib/info.c.o
[ 24%] Building C object CMakeFiles/ktx_read.dir/lib/memstream.c.oLin
The Windows Subsystem for Linux (WSL) has no installed distributions.
To resolve this issue, you can install a distribution by following these instructions:

Use wsl.exe --list --online to list available distributions.
Use wsl.exe --install <Distro> to install the desired distribution.
mingw32-make[2]: *** [CMakeFiles\ktx_version.dir\build.make:72: C:/Users/asus/.conan2/p/b/ktx74fa4444ddabd/b/src/lib/version.h] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:1139: CMakeFiles/ktx_version.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
[ 24%] Building C object CMakeFiles/ktx_read.dir/lib/strings.c.o
[ 25%] Building C object CMakeFiles/ktx_read.dir/lib/swap.c.o
[ 26%] Building C object CMakeFiles/ktx_read.dir/lib/texture.c.o
[ 28%] [ 28%] Building C object CMakeFiles/ktx_read.dir/lib/texture2.c.oBuilding C object CMakeFiles/ktx_read.dir/lib/vkformat_check.c.o

[ 30%] [ 30%] Building C object CMakeFiles/ktx_read.dir/lib/vkformat_typesize.c.oBuilding C object CMakeFiles/ktx_read.dir/lib/vkformat_str.c.o

[ 31%] Building C object CMakeFiles/ktx_read.dir/lib/gl_funcs.c.o
[ 32%] Building C object CMakeFiles/ktx_read.dir/lib/glloader.c.o
[ 33%] Building C object CMakeFiles/ktx_read.dir/lib/texture1.c.o
[ 35%] [ 35%] Building C object CMakeFiles/ktx_read.dir/lib/vk_funcs.c.oBuilding C object CMakeFiles/ktx_read.dir/lib/vkloader.c.o

[ 36%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_decompress_symbolic.cpp.o
[ 37%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_diagnostic_trace.cpp.o
[ 38%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_entry.cpp.o
[ 39%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_find_best_partitioning.cpp.o
[ 40%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_ideal_endpoints_and_weights.cpp.o
[ 41%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_image.cpp.o
[ 42%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_integer_sequence.cpp.o
[ 43%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_mathlib.cpp.o
[ 44%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_mathlib_softfloat.cpp.o
[ 45%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_partition_tables.cpp.o
[ 46%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_percentile_tables.cpp.o
[ 46%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_pick_best_endpoint_format.cpp.o
[ 47%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_quantization.cpp.o
[ 48%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_symbolic_physical.cpp.o
[ 49%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_weight_align.cpp.o
[ 50%] Building CXX object lib/astc-encoder/Source/CMakeFiles/astcenc-none-static.dir/astcenc_weight_quant_xfer_tables.cpp.o
[ 51%] Linking CXX static library libobjUtil.a
[ 52%] Linking CXX static library libobj_basisu_cbind.a
[ 52%] Built target objUtil
[ 52%] Built target obj_basisu_cbind
[ 53%] Linking CXX static library libastcenc-none-static.a
[ 53%] Built target astcenc-none-static
[ 54%] Linking CXX static library libktx_read.a
[ 54%] Built target ktx_read
mingw32-make: *** [Makefile:165: all] Error 2

ktx/4.3.2: ERROR:
Package 'e219cd982539d29b3fb2ee3a7f58d5c6b63fd3fd' build failed
ktx/4.3.2: WARN: Build folder C:\Users\asus\.conan2\p\b\ktx74fa4444ddabd\b\build\Release
ERROR: ktx/4.3.2: Error in build() method, line 135
        cmake.build()
        ConanException: Error 2 while executing

**Comment by Nekto89** [comment]
I suspect that something should be done with tools.microsoft.bash (maybe msys2 in tool_requires?) to provide BASH_EXECUTABLE but I don't have any experience with it.
https://github.com/KhronosGroup/KTX-Software/blob/70ed9b9c5cb80867a045beffb0f1ef92e6648db3/cmake/version.cmake#L180
https://github.com/KhronosGroup/KTX-Software/blob/70ed9b9c5cb80867a045beffb0f1ef92e6648db3/cmake/modules/FindBash.cmake#L5

**Comment by longye-wwb** [comment]
> I suspect that something should be done with tools.microsoft.bash (maybe msys2 in tool_requires?) to provide BASH_EXECUTABLE but I don't have any experience with it. https://github.com/KhronosGroup/KTX-Software/blob/70ed9b9c5cb80867a045beffb0f1ef92e6648db3/cmake/version.cmake#L180 https://github.com/KhronosGroup/KTX-Software/blob/70ed9b9c5cb80867a045beffb0f1ef92e6648db3/cmake/modules/FindBash.cmake#L5

Thank you for your suggestions. For now, I've adopted the approach of locally integrating the KTX library into my project. This issue doesn't require further resolution at the moment.
