### ISSUE TITLE
[request] libx265/4.1 + recipe refactor/new features

### ISSUE THREAD

**Issue by jsobo-dlb** [conan-io/conan-center-index#29034]
### Package Name/Version

libx265/4.1

### Changelog

https://bitbucket.org/multicoreware/x265_git/src/Release_4.1/

### Context about the new update

Current recipe [libx265/3.6](https://conan.io/center/recipes/libx265?version=3.6) is outdated. Version 4.1 is available and fixes some issues, such as macos arm build with assembly enabled.

Apart from the update, current recipe has severe limitations:
- lack of multi-bitdepth support: the library offers combining multiple bitdepths into single binary (8+10+12bit). Basically the library is built 3 times, twice as a 'backend' library and once as a 'frontend' library that distributes the api calls to itself or the backend libraries.
- lack of many useful options, such as:
  - `multiview` toogle
  - toggling AArch64 SIMD extensions:
    - `with_neon`
    - `with_neon_dotprod`
    - `with_neon_i8mm`
    - `with_sve`
    - `with_sve2`

I can open a PR that addresses the above issues. With how much the recipe and libx265 changes, I don't see the point in keeping older versions supported. I'd like to keep my PR solely focused around the latest version.

My team uses this recipe on production for macos arm/x86, linux arm/x86, windows x86, so I'm fairly certain those flavors works. I'm not aware of what is expected to be supported, but the recipe I'd like to present offers build workflow much more on pair with what x265 developers suggest, so I think it will be much easier to maintain and extend to support other platforms.

**Comment by uilianries** [comment]
Hello! This issue is now fixed by #28966

Please, update your local copy to the latest version available:

    conan install -r conancenter --update --requires=libx265/4.1

Regards!

**Comment by jsobo-dlb** [comment]
It's not fixed. Only 4.1 has been added, but the features I listed are still missing. I didn't find time to prepare a PR yet, but I want this issue so I can refer to it eventually.

**Comment by uilianries** [comment]
@jsobo-dlb Hello, sorry, closing your issue is not fulfilled. Also, please try to open separate issues when requesting a bump version and new features in the future, as they can get complex to resolve. 

About those new options: 

Conan 2.x includes a feature that lets you pass extra definitions to CMake without increasing the number of options in the recipe, nor changing the recipe and releasing a new recipe revision: the Conan configuration `tools.cmake.cmaketoolchain:extra_variables`. So you can add it directly to your Conan profile, and it will override values already defined in the recipe. For your specific case, you can do:

```ini
# ~/.conan2/profiles/default

[conf]
# Injects the CMake variable during the build of libx265 only to disable Neon
libx265/*:tools.cmake.cmaketoolchain:extra_variables={"ENABLE_NEON": "OFF"}
# Ensures the package ID changes so it doesn't collide with the default build
libx265/*:tools.info.package_id:confs=["tools.cmake.cmaketoolchain:extra_variables"]
```

This update in your Conan profile will inject the CMake definition `ENABLE_NEON` via the Conan generator `CMakeToolchain`. Also, it may produce a different package and it will collide with the default package ID, the conf `tools.info.package_id:confs` will change the package ID according to `extra_variables`. As all those configurations start with `libx265/*`, it means they will be applied only to **libx265** and for any version.

As for adding a new option in ConanCenterIndex, it's generally preferable to avoid it if it's not crucial, like dependency management or important features, since options require additional maintenance and validations that aren’t covered by the default CI; for example, building locally with both ON/OFF values and uploading the logs to check the package building results.

We have several cases from the past where packages were broken when switching an option that CI did not validate. When changing a recipe to add a new option, it not only results in a new recipe revision but also changes the package ID, affecting those packages that consume this one and users who will need to update their copies, too. And, libx265 is used by ffmpeg, so this change may affect several users who may not be interested in this change directly.

It does not mean new options are not accepted, but we usually prefer general cases, like dependencies or crucial options that have a quorum in an open issue asking about, as we will need to verify the options' effect closely before adding them, and review them again for new versions of the package.

-----

On the other hand, it does not stop you from distributing a changed revision of the recipe for `libx265` to other users around GitHub who are using Conan: You can use a few features that may make this possible across your own fork:

* Consumers can use a [local recipes index](https://docs.conan.io/2/tutorial/conan_repositories/setup_local_recipes_index.html) and point your GitHub fork as a new remote: They will be able to consume your changed recipes, not only for libx265, but for any other customization around. Initially, it will make only the Conan recipe available, so they can export and build it locally or in a build machine/service.

* Use an [Artifactory](https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes/artifactory/artifactory_ce_cpp.html) instance to publish your pre-built packages if operating it in an enterprise. So your teammates can download from a centralized instance, instead of consuming from Conan Center and being dependent of internet connection.

* For small experiments, or even very small teams, you may prove [Conan Server](https://docs.conan.io/2/reference/conan_server.html#conan-server) enough in case wanting to distribute artifacts, include pre-built packages, but running a small server on your machine, for instance.

I hope I have clarified for you why preferring using those alternatives, instead of changing the current recipe with those new options. These alternatives are pretty stable and mature enough, and should fit most cases needing a new customization in the recipe. Feel free to share your thoughts, regards.

**Comment by jsobo-dlb** [comment]
Thanks for the input. Using `cmaketoolchain:extra_variable` to set the options I listed indeed seems like a good idea and does not clutter the recipe as you explained - that's something I haven't considered. I'll also discuss the rest of what you wrote with my team, thank you.

I don't think this solves the lack of multi-bitdepth support though, as the option `"bit_depth": [8, 10, 12],` simply does not cover the multi-bitdepth use case, which I believe is useful, since you cannot `require` multiple `libx265` with different options. Without additional option it's impossible to have a full range of bitdepth support if one's application needs it (see [Multilib build instructions](https://bitbucket.org/multicoreware/x265_git/wiki/Home) section).

It also [doesn't support arm with assembly compilation](https://github.com/conan-io/conan-center-index/blob/master/recipes/libx265/all/conanfile.py#L89), even though it could. 

I think we can keep this issue closed and I can create a different one specifically focused around those two issues, unless you don't consider these changes impactful enough?

**Comment by uilianries** [comment]
> I think we can keep this issue closed and I can create a different one specifically focused around those two issues, unless you don't consider these changes impactful enough?

Yes, please, you can open a new issue focused on those options. Also, try to be detailed about your need too, as it helps not only maintainers, but also other people interested in the same case. Regards.
