### ISSUE TITLE
[package] Boost/1.90.0: build error on Linux

### ISSUE THREAD

**Issue by gav2xlin** [conan-io/conan-center-index#29193]
### Description

There's an error. I tried this release and got an error. My build type was Debug.

boost/1.90.0: Package folder /home/gav2xlin/.conan2/p/b/boost248117d998be8/p
ERROR: boost/1.90.0: Error in package_info() method, line 2024
raise ConanException(f"These libraries were built, but were not used in any boost module: {non_used}")
ConanException: These libraries were built, but were not used in any boost module: {'boost_cobalt_io_ssl'}

It repeats without any conanfile files.

boost cobalt io ssl is here (as I see):
https://github.com/boostorg/cobalt/blob/10fa59946e1bb8413c32802cc089dafa644ec814/src/io/ssl.cpp

### Package and Environment Details

* Package Name/Version: **boost/1.90.0**
* Operating System+version: **Ubuntu 25.10**
* Compiler+version: **GCC 15.2.0**
* Conan version: **conan 2.24.0**
* Python version: **Python 3.11.13**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu23
compiler.cstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=15
os=Linux

### Steps to reproduce

conan create . --version=1.90.0 --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
======== Installing packages ========
bzip2/1.0.8: Already installed! (1 of 4)
libbacktrace/cci.20210118: Already installed! (2 of 4)
zlib/1.3.1: Already installed! (3 of 4)
boost/1.90.0: Already installed! (4 of 4)
ERROR: boost/1.90.0: Error in package_info() method, line 2024
	raise ConanException(f"These libraries were built, but were not used in any boost module: {non_used}")
	ConanException: These libraries were built, but were not used in any boost module: {'boost_cobalt_io_ssl'}
```

</details>

**Comment by mologie** [comment]
I'm getting a related/similar error:
```
ERROR: boost/1.90.0: Error in package_info() method, line 2024
	raise ConanException(f"These libraries were built, but were not used in any boost module: {non_used}")
	ConanException: These libraries were built, but were not used in any boost module: {'boost_container'}
```

Using this choker to configure Boost since unfortunately all libs are on by default:
```
    default_options.update({f"boost/*:without_{name}": True for name in [
        "atomic", "charconv", "chrono", "cobalt", "container", "context", "contract", "coroutine",
        "date_time", "exception", "fiber", "filesystem", "graph", "graph_parallel", "iostreams",
        "json", "locale", "log", "math", "mpi", "nowide", "process", "python", "random", "regex",
        "serialization", "stacktrace", "test", "thread", "timer", "type_erasure", "wave"
    ]})
```

Boost container shows up as "not building" in the build output, yet the exception says it's there, not sure what's happening but the 1.90 release here in Conan seems broken right now.

**Comment by jcar87** [comment]
Thanks @gav2xlin and @mologie 

Please post the entire build log of the command you are running, including:
- the bit at the top where Conan prints the profile configuration
- the entirety of the boost build log (the error in the package_info() is usually better understood if we can see what the boost configurator reported)

it would be great if you could also pass `-c:a tools.build:verbosity=verbose` as the boost recipe is configured to output more information in that case, thanks!

**Comment by gav2xlin** [comment]
@jcar87 attached

[build.log](https://github.com/user-attachments/files/24293496/build.log)

**Comment by uilianries** [comment]
@gav2xlin @mologie Out of curiosity, are you using Boost Cobalt?

**Comment by uilianries** [comment]
I have just updated PR #26059 to include a fix for this issue as well. The Boost.Cobalt introduced some bugs in the package since its introduction in the recipe. I discussed with Memsharded some time ago to keep it disabled by default to avoid breaking users, as it requires C++20 to be enabled.

**Comment by mologie** [comment]
@uilianries I'm afraid that even with your PR applied (`gh pr checkout 26059 && git rebase origin/master && conan export --version 1.90.0 all`, then inserted that into `conan.lock`), the issue still reproduces for me on 2.24.0, macOS 26.2 arm64, Xcode 26.2.

I'm attaching build log with `-c:a tools.build:verbosity=verbose`, where most boost libraries except program_options and url are off. b2 claims that container will not be built, yet it is and that (correctly) trips the recipe:

[conan-boost-1.9.0-build.log](https://github.com/user-attachments/files/24298372/conan-boost-1.9.0-build.log)

Edit: My build profile:

```
$ cat ~/.conan2/profiles/default
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu23
compiler.libcxx=libc++
compiler.version=17
os=Macos
```

**Comment by mologie** [comment]
> [@gav2xlin](https://github.com/gav2xlin) [@mologie](https://github.com/mologie) Out of curiosity, are you using Boost Cobalt?

To not leave that one unanswered, no, I am not using Cobalt and explicitly turn it off.

It appears the workaround for this issue I'm having is to leave `with_container` on. If it's off, then the recipe crashes with the described exception.

**Comment by uilianries** [comment]
@mologie Thank you for the information and build log! I'll be investigating it.

**Comment by uilianries** [comment]
@mologie I'm able to reproduce your case using a similar scenario: [boost-1.90.0-osx-aarch64-clang17-release-static.log](https://github.com/user-attachments/files/24307955/boost-1.90.0-osx-aarch64-clang17-release-static.log)

It's important to note your are not using the exactly recipe as from that PR: The recipe revision from your log is not the same from the PR and my log: `f5a7e8f9032db9888aefba29e8a8f713`, please, make sure using the exact same recipe to avoid possible differences when building.

Still, I'm afraid you spotted another unexpected scenario related to Boost internal dependencies, not the first in those last versions. The PR #26059 is about Boost Cobalt and indeed it uses Boost container as a dependency, but it's not the only one. With the introduction of modular Boost, even when you say during the setup to "not build module X" and the setup says "X: not building", in case any library which needs module X is built, the X library will be built too. And it's not easy track it down, because it maybe transitive dependencies as well, not a direct dependency.

I'll report your case in Boost directly, as I don't see it connected to Cobalt, it can be one of those header libraries that need boost container instead. To validate it's not Cobalt, I made a change in the recipe, to not only disable Container option in Cobalt, but also erase from its build to make it will not be consumed as a mistake:

```diff
diff --git a/recipes/boost/all/conanfile.py b/recipes/boost/all/conanfile.py
index 37eefc86b6..5fc2f190be 100644
--- a/recipes/boost/all/conanfile.py
+++ b/recipes/boost/all/conanfile.py
@@ -152,8 +152,6 @@ class BoostConan(ConanFile):
     default_options.update({f"without_{_name}": False for _name in CONFIGURE_OPTIONS})
     default_options.update({f"without_{_name}": True for _name in ("graph_parallel", "mpi", "python", "cobalt")})
 
-    short_paths = True
-    no_copy_source = True
     _cached_dependencies = None
 
     def export(self):
@@ -857,6 +855,10 @@ class BoostConan(ConanFile):
         get(self, **self.conan_data["sources"][self.version],
             destination=self.source_folder, strip_root=True)
         apply_conandata_patches(self)
+        rm(self, "Jamfile", os.path.join(self.source_folder, "libs", "container_hash", "benchmark"))
+        replace_in_file(self, os.path.join(self.source_folder, "libs", "cobalt", "build", "Jamfile"),
+                "<boost.cobalt.pmr>boost-container:<library>/boost/container//boost_container",
+                "")
 
     def generate(self):
         if not self.options.header_only:
@@ -1441,7 +1443,7 @@ class BoostConan(ConanFile):
             # INFO: https://gcc.gnu.org/wiki/cxx-coroutines
             if self.settings.compiler == "gcc" and Version(self.settings.compiler.version) == "10":
                 cxx_flags.append("-fcoroutines")
-            flags.append('boost.cobalt.pmr=boost-container')
+        flags.append('boost.cobalt.pmr=no')
 
         cxx_flags = f'cxxflags="{" ".join(cxx_flags)}"'
         flags.append(cxx_flags)
```

Still, even using the version option set that you pointed, url=True program_options=True, Boost container is still produced. It's true both don't use Boost container directly, but they use other dependencies that should require Container.


**UPDATE**: I just opened the issue https://github.com/boostorg/program_options/issues/152 reporting the case.

**Comment by Hailios** [comment]
this is still the case from what I can see. linked PR looks like it has stalled, and the issue reported to boost got closed without changes.

**Comment by yawin123** [comment]
Hi, I'm just here to remind everyone that this problem is still happening and the Boost team has washed their hands of it, claiming that "the change is in another part of the building infrastructure."

**Comment by offa** [comment]
For those still running into this problem (and don't need cobalt):

##### conanfile.txt
```
[options]
boost/*:without_cobalt=True
```

##### conanfile.py
```
def configure(self):
    self.options["boost"].without_cobalt = True
```
