### ISSUE TITLE
[package] protobuf: can't mimic correct CMake variables from upstream

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#3492]
As @uilianries described here: https://github.com/conan-io/conan-center-index/pull/2037 Protobuf is using:

  * `Protobuf_` prefixed CMake variables
  * `protobuf::` namespaced CMake targets
  * and `Protobuf` prefixed CMake file names

We currently match the CMake targets and the CMake file names, but we don't match the CMake variables.

This might be important for full compatible with the CMake functions Protobuf is exposing to consumers.

We should figure out
  * if this has an actual negative impact or if it isn't relevant
  * and if it is relevant, how to get there. Do we find a workaround? Do we have to extend Conan's features?

**Comment by sourcedelica** [comment]
From my perspective the most important thing is for `protobuf_generate_cpp` and `protobuf_generate_python` to work.  These functions depend on certain variable/targets being defined historically by `find_package(Protobuf)`.  However, there may be other packages that depend on other variable/targets (grpc?)

**Comment by Hopobcn** [comment]
@sourcedelica #2037 `test_package`  uses `protobuf_generate_cpp` so this part is covered. (python method is not tested but If I remember well it's also defined in the same file as `protobuf_generate_cpp` so it should work too)

**Comment by Croydon** [comment]
Referencing as this is one of many places where Protobuf does expect certain variables:

https://github.com/conan-io/conan-center-index/pull/2037/files#r515663456

**Comment by Croydon** [comment]
This should be now possible in a similar way then what @SpaceIm has done for OpenSSL: https://github.com/conan-io/conan-center-index/commit/8e2f2f97f2631ffe86c53ffb7e4cec44a0206806

**Comment by anton-danielsson** [comment]
Fixed in https://github.com/conan-io/conan-center-index/pull/4776?
Or is something more missing?

**Comment by Croydon** [comment]
I don't recall there might be more variables missing. I will have a look next week

**Comment by SpaceIm** [comment]
For sure #4776 didn't change CMake variables provided by `cmake_find_package`, of it was broken before this PR, it's still broken after ;)

**Comment by HerrNamenlos123** [comment]
Is this issue still active? I'm having the same issue.
I use `find_package(protobuf REQUIRED)` and i get tons of cmake warnings about capitalization and at some point it even stopped working completely. I use `CMakeToolChain` and `CMakeDeps` generators and many protobuf related files are generated. All contents of them are completely lowercase, except the file `FindProtobuf.cmake`, in this file everything starts with a capital P. When going through this file and changing everything to lowercase then all issues are completely resolved.

I noticed in the conanfile for protobuf, everything is lowercase except a few occurrences. Like here: 
https://github.com/conan-io/conan-center-index/blob/a89e737f7001d0d01308e0a4e9b674d94588dcb2/recipes/protobuf/all/conanfile.py#L279
Couldn't this all be changed to lowercase, resolving all issues?

**Comment by HerrNamenlos123** [comment]
And yes, there are packages that use `find_package(Protobuf)`, but find_package can either find `FindProtobuf` or `protobuf-targets`, so either one of these cannot work.

As a side note, what happens if cmake finds both `FindProtobuf.cmake` and `Findprotobuf.cmake`, will it just load the one with the right capitalization?

**Comment by Croydon** [comment]
I didn't use the protobuf recipe myself in a long time and don't know the current state of it.

Closing this. If this is still a problem someone else can open a new issue with more up-to-date information.
