### ISSUE TITLE
[question] qt macdeployqt can not find any external Qt frameworks

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#5555]
When using `macdeployqt` from `qt/6.0.4` and trying to deploy app on Macos 11.1 I am getting log like:

```
WARNING:
WARNING: Could not find any external Qt frameworks to deploy in  <path_to_app>
WARNING: Perhaps macdeployqt was already used on <path_to_app> ?
WARNING: If so, you will need to rebuild <path_to_app>before trying again.
```

Nothing gets deployed into the app package.
I am invoking deploy command like:
```
/.conan/data/qt/6.0.4/_/_/package/a2399dc89626f20f48cd5d81b87556fdd92f98dc/bin/macdeployqt <path_to_app> -verbose=2
```

The same command with `macdeployqt` from manual qt6 installation works fine and package gets deployed.
Here is the content of `qt.conf` from qt6 conan package:
```
[Paths]
Prefix = ..
ArchData = res/archdatadir
HostData = res/archdatadir
Data = res/datadir
Sysconf = res/sysconfdir
LibraryExecutables = res/archdatadir/bin
Plugins = res/archdatadir/plugins
Imports = res/archdatadir/imports
Qml2Imports = res/archdatadir/qml
Translations = res/datadir/translations
Documentation = res/datadir/doc
```

Is there anything I have to adjust in this flow?

**Comment by yuriy-mochurad** [comment]
@ericLemanissier I am not sure if it is related to #5487. That issue refers to qt5.x.x and also it has different paths, e.g.

- qt5 from bug above:
```
Plugins = bin/archdatadir/plugins
```
- while in qt6 I can see:
```
Plugins = res/archdatadir/plugins
```
The one in qt6 looks correct to me.

The issue from qt https://bugreports.qt.io/browse/QTBUG-91644  - looks similar to what I am seeing, but it also says that it was fixed in qt6.0.2. Also `macdeployqt` from version 6.0.4 that comes with official qt installer works fine.

**Comment by yuriy-mochurad** [comment]
@ericLemanissier so do you mean that issue is on Qt side, and from conan package point of view there is no way to fix/patch it?

**Comment by ericLemanissier** [comment]
Yes. It should also be fixed in qt 6.1.1

**Comment by yuriy-mochurad** [comment]
@ericLemanissier unfortunately it looks like the issue us still present in 6.1.1 even with the fix from QTBUG-91644 being present.
Plugins are not getting deployed, even if path by `macdeployqt` is detected correctly:

```
Log: Deploying plugins from "~/.conan/data/qt/6.1.1/_/_/package/4154e1fbfdd6517f82c085fe4e146699f3897b83/res/archdatadir/plugins"
```

**Comment by yuriy-mochurad** [comment]
Interesting enough, when I recompiled `qt/6.1.1` with `"qt:shared": True` option, `macdeployqt` worked as expected.

**Comment by ericLemanissier** [comment]
AFAIU, when qt is static, the plugins are also static, so there is nothing to deploy in this case right ?

**Comment by yuriy-mochurad** [comment]
Well, my app was complaining that it can not find `cocoa` plugin, so I guess some need to be deployed. But this is something that needs additional research

**Comment by ericLemanissier** [comment]
I'm not sure, but maybe you need to use https://doc.qt.io/qt-6/qt-import-plugins.html?

**Comment by yuriy-mochurad** [comment]
Yeah, that might help. In any case, thank you for your support @ericLemanissier .
I am closing this issue
