### ISSUE TITLE
QT qt/5.15.2: Linking failure in MSVC 16

### ISSUE THREAD

**Issue by fragrans** [conan-io/conan-center-index#6492]
LINK : fatal error LNK1181: cannot open input file 'Qt5SvgWidgets.lib' [D:\gitee.com\superbot\build\qt\cpk.vcxproj]

This configuration works good on my other windows 10 computer however.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: qt/5.15.2
  * Operating System+version: Windows 10
  * Compiler+version: msvc v16.10.4
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.9.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
❯ conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

```
❯ cat ..\qt\conanfile.txt
[requires]
zlib/1.2.11
boost/1.76.0
lua/5.4.1
libcurl/7.75.0
opencv/4.5.2
jsoncpp/1.9.4
sqlite3/3.35.5
yaml-cpp/0.6.3
uwebsockets/19.2.0
qt/5.15.2
zstd/1.5.0
fmt/8.0.0

[generators]
cmake
cmake_find_package

[options]
qt:shared=True
# qt:with_zstd=False
qt:with_sqlite3=False
qt:with_mysql=False
qt:with_pq=False
qt:with_odbc=False
qt:qtdeclarative=True
qt:qtquickcontrols2=True
qt:gui=True
qt:widgets=True
qt:qtsvg=True

[imports]
bin, *.dll -> ./bin @ folder=False
# res/archdatadir/plugins, * -> ./bin @ root_package=qt
# res/archdatadir/qml, * -> ./bin @ root_package=qt

bin/archdatadir/plugins, * -> ./bin @ root_package=qt
bin/archdatadir/qml, * -> ./bin @ root_package=qt
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
LINK : fatal error LNK1181: cannot open input file 'Qt5SvgWidgets.lib' [D:\gitee.com\superbot\build\qt\cpk.vcxproj]
```
```
❯ conan install ..\qt\
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    boost/1.76.0 from 'conan-center' - Cache
    brotli/1.0.9 from 'conan-center' - Cache
    bzip2/1.0.8 from 'conan-center' - Cache
    double-conversion/3.1.5 from 'conan-center' - Cache
    eigen/3.3.9 from 'conan-center' - Cache
    fmt/8.0.0 from 'conan-center' - Cache
    freetype/2.10.4 from 'conan-center' - Cache
    jasper/2.0.32 from 'conan-center' - Cache
    jbig/20160605 from 'conan-center' - Cache
    jsoncpp/1.9.4 from 'conan-center' - Cache
    libcurl/7.75.0 from 'conan-center' - Cache
    libdeflate/1.7 from 'conan-center' - Cache
    libjpeg/9d from 'conan-center' - Cache
    libpng/1.6.37 from 'conan-center' - Cache
    libtiff/4.2.0 from 'conan-center' - Cache
    libuv/1.41.0 from 'conan-center' - Cache
    libwebp/1.2.0 from 'conan-center' - Cache
    lua/5.4.1 from 'conan-center' - Cache
    opencv/4.5.2 from 'conan-center' - Cache
    openexr/2.5.5 from 'conan-center' - Cache
    opengl/system from 'conan-center' - Cache
    openssl/1.1.1k from 'conan-center' - Cache
    pcre2/10.37 from 'conan-center' - Cache
    protobuf/3.15.5 from 'conan-center' - Cache
    qt/5.15.2 from 'conan-center' - Cache
    quirc/1.1 from 'conan-center' - Cache
    sqlite3/3.35.5 from 'conan-center' - Cache
    usockets/0.7.1 from 'conan-center' - Cache
    uwebsockets/19.2.0 from 'conan-center' - Cache
    xz_utils/5.2.5 from 'conan-center' - Cache
    yaml-cpp/0.6.3 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
    zstd/1.5.0 from 'conan-center' - Cache
Packages
    boost/1.76.0:a60baac5107ef779a5865836fcb50c28ae423a0b - Cache
    brotli/1.0.9:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
    double-conversion/3.1.5:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    fmt/8.0.0:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    freetype/2.10.4:27b2733304cef577b19f699fec3a5bdbefb36d16 - Cache
    jasper/2.0.32:264d5d4a0e3e283cd524e2a58344075802f4577c - Cache
    jbig/20160605:1c06f8aa5b65435590877732bd94377a1ed95260 - Cache
    jsoncpp/1.9.4:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libcurl/7.75.0:c708807bd7d96d499cc7ef633e8546ec246ba1b3 - Cache
    libdeflate/1.7:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libjpeg/9d:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libpng/1.6.37:d140711d95cc16a85766a8fc3a551dfafe84cf63 - Cache
    libtiff/4.2.0:a08a8e56550da57f6f3d93bb076a90cc6c19cfa2 - Cache
    libuv/1.41.0:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libwebp/1.2.0:638042d3fd356128c913f5e725646a0c2af264c7 - Cache
    lua/5.4.1:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    opencv/4.5.2:7bbb424cd5f45d5f2186b3cc716d6daa65021c9c - Cache
    openexr/2.5.5:d140711d95cc16a85766a8fc3a551dfafe84cf63 - Cache
    opengl/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    openssl/1.1.1k:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    pcre2/10.37:c3909bc59b2700f5c593b64eb3cdec0e85b05bc5 - Cache
    protobuf/3.15.5:9e56137bbb1f5dae27f8e6f5a1977466799557b9 - Cache
    qt/5.15.2:ea5748f1ec2990aa53cf26eafa1096b558dafa2f - Cache
    quirc/1.1:8e7d69ac1d5596196386f046159aacd9644a7227 - Cache
    sqlite3/3.35.5:050fb3a4d3559ab088bce91739e61889c28839d1 - Cache
    usockets/0.7.1:e47032debdb048e9047e7ad5d0500bdc37a5deee - Cache
    uwebsockets/19.2.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    xz_utils/5.2.5:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    yaml-cpp/0.6.3:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    zlib/1.2.11:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    zstd/1.5.0:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

Installing (downloading, building) binaries...
brotli/1.0.9: Already installed!
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: C:\Users\Liang\.conan\data\bzip2\1.0.8\_\_\package\d16a91eadaaf5829b928b12d2f836ff7680d3df5\bin
double-conversion/3.1.5: Already installed!
eigen/3.3.9: Already installed!
fmt/8.0.0: Already installed!
jbig/20160605: Already installed!
jbig/20160605: Appending PATH environment variable: C:\Users\Liang\.conan\data\jbig\20160605\_\_\package\1c06f8aa5b65435590877732bd94377a1ed95260\bin
jsoncpp/1.9.4: Already installed!
libdeflate/1.7: Already installed!
libjpeg/9d: Already installed!
libuv/1.41.0: Already installed!
libwebp/1.2.0: Already installed!
lua/5.4.1: Already installed!
opengl/system: Already installed!
openssl/1.1.1k: Already installed!
quirc/1.1: Already installed!
sqlite3/3.35.5: Already installed!
sqlite3/3.35.5: Appending PATH env var with : C:\Users\Liang\.conan\data\sqlite3\3.35.5\_\_\package\050fb3a4d3559ab088bce91739e61889c28839d1\bin
xz_utils/5.2.5: Already installed!
yaml-cpp/0.6.3: Already installed!
zlib/1.2.11: Already installed!
zstd/1.5.0: Already installed!
boost/1.76.0: Already installed!
boost/1.76.0: Disabled magic autolinking (smart and magic decisions)
jasper/2.0.32: Already installed!
libcurl/7.75.0: Already installed!
libpng/1.6.37: Already installed!
libtiff/4.2.0: Already installed!
openexr/2.5.5: Already installed!
pcre2/10.37: Already installed!
pcre2/10.37: Appending PATH environment variable: C:\Users\Liang\.conan\data\pcre2\10.37\_\_\package\c3909bc59b2700f5c593b64eb3cdec0e85b05bc5\bin
protobuf/3.15.5: Already installed!
protobuf/3.15.5: Appending PATH environment variable: C:\.conan\8fb7e0\1\bin
usockets/0.7.1: Already installed!
freetype/2.10.4: Already installed!
opencv/4.5.2: Already installed!
uwebsockets/19.2.0: Already installed!
qt/5.15.2: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator cmake_find_package created FindBoost.cmake
conanfile.txt: Generator cmake_find_package created Findlua.cmake
conanfile.txt: Generator cmake_find_package created FindCURL.cmake
conanfile.txt: Generator cmake_find_package created FindOpenCV.cmake
conanfile.txt: Generator cmake_find_package created Findjsoncpp.cmake
conanfile.txt: Generator cmake_find_package created FindSQLite3.cmake
conanfile.txt: Generator cmake_find_package created Findyaml-cpp.cmake
conanfile.txt: Generator cmake_find_package created Finduwebsockets.cmake
conanfile.txt: Generator cmake_find_package created FindQt5.cmake
conanfile.txt: Generator cmake_find_package created Findfmt.cmake
conanfile.txt: Generator cmake_find_package created FindOpenSSL.cmake
conanfile.txt: Generator cmake_find_package created FindJasper.cmake
conanfile.txt: Generator cmake_find_package created FindOpenEXR.cmake
conanfile.txt: Generator cmake_find_package created FindTIFF.cmake
conanfile.txt: Generator cmake_find_package created FindEigen3.cmake
conanfile.txt: Generator cmake_find_package created Findquirc.cmake
conanfile.txt: Generator cmake_find_package created FindProtobuf.cmake
conanfile.txt: Generator cmake_find_package created Findusockets.cmake
conanfile.txt: Generator cmake_find_package created Findpcre2.cmake
conanfile.txt: Generator cmake_find_package created Finddouble-conversion.cmake
conanfile.txt: Generator cmake_find_package created FindFreetype.cmake
conanfile.txt: Generator cmake_find_package created Findopengl_system.cmake
conanfile.txt: Generator cmake_find_package created FindBZip2.cmake
conanfile.txt: Generator cmake_find_package created FindJPEG.cmake
conanfile.txt: Generator cmake_find_package created FindPNG.cmake
conanfile.txt: Generator cmake_find_package created Findlibdeflate.cmake
conanfile.txt: Generator cmake_find_package created FindLibLZMA.cmake
conanfile.txt: Generator cmake_find_package created Findjbig.cmake
conanfile.txt: Generator cmake_find_package created Findzstd.cmake
conanfile.txt: Generator cmake_find_package created FindWebP.cmake
conanfile.txt: Generator cmake_find_package created Findlibuv.cmake
conanfile.txt: Generator cmake_find_package created FindBrotli.cmake
conanfile.txt: Generator cmake_find_package created FindZLIB.cmake
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
conanfile.txt imports(): Copied 352 '.qml' files
conanfile.txt imports(): Copied 132 '.dll' files
conanfile.txt imports(): Copied 87 '.png' files
conanfile.txt imports(): Copied 28 '.qmltypes' files
conanfile.txt imports(): Copied 28 files
conanfile.txt imports(): Copied 1 '.metainfo' file: qtquickcontrols2.metainfo
conanfile.txt imports(): Copied 1 '.js' file: testlogger.js
```

</details>

**Comment by ericLemanissier** [comment]
This should have been solved by https://github.com/conan-io/conan-center-index/pull/6235
Please update the recipe with -u argument and retry

**Comment by fragrans** [comment]
No, it still isn't working. 
I used --build=missing option btw.

**Comment by fragrans** [comment]
![image](https://user-images.githubusercontent.com/102768/126898550-f9c23a91-f155-4a2d-ab16-a8700d82561a.png)
The creation date does not change. after I use:
```
conan install ..\conanfile.txt -u
```
I don't know why. 
Is there any other proper way to update a specific recipe?

**Comment by ericLemanissier** [comment]
The other way to force the update is to remove the qt folder in ~/.conan/data/qt
Please send the full log if the error still happens

**Comment by maksim-0** [comment]
@fragrans you're using wrong remote address, it should be https://center.conan.io instead of https://conan.bintray.com. See #6425

**Comment by fragrans** [comment]
Thanks, @maksim-0.
That helps the case, the creation date updated to 07-23.
I've thought that the default remote will point to the new https://center.conan.io instead of the deprecated one.

Though I still don't know the proper way to synchronize local recipes to remote ones;
