### ISSUE TITLE
sdl package video options seem to not have any impact 

### ISSUE THREAD

**Issue by positivcheg94** [conan-io/conan-center-index#8617]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl/2.0.18**
  * Operating System+version: **Windows10**
  * Compiler+version: **MSVC 17**
  * Conan version: **conan 1.44.0**

### Steps to reproduce

So from my observation, it does look like options provided by the sdl conan package and OpenGL, OpenGLES, DirectX, Vulkan seem to not have any impact on library build.

Why is it though?
To prove my point.

1. I found it strange that when I load my app in visual studio it loads DLLs on startup such as
```
'ApplicationExample.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. 
'ApplicationExample.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'.
```
2. in .conan\data\sdl\2.0.18\_\_\build\164640aad040835ac89882393a96d89200694f04\build_subfolder if I check CMakeCache.txt it shows cached variables for graphics backends
```
//Include OpenGL support
SDL_OPENGL:BOOL=ON
//Include OpenGL ES support
SDL_OPENGLES:BOOL=ON
```
3. Also from the build log of conan install I see
--   SDL_OPENGL                  (Wanted: ON): ON
--   SDL_OPENGLES                (Wanted: ON): ON

So all of that makes me assume that either package is not picking correctly the options or am I doing something wrong?
In that conan package build folder .conan\data\sdl\2.0.18\_\_\build\164640aad040835ac89882393a96d89200694f04 conaninfo.txt seem to pick correctly options that I've provided in my project's conanfile.py though default_options - `"sdl:opengl":False`

```
[settings]
    arch=x86_64
    build_type=Debug
    compiler=Visual Studio
    compiler.runtime=MDd
    compiler.version=17
    os=Windows

[requires]


[options]
    directx=False
    opengl=False
    opengles=False
    shared=False
    vulkan=False

[full_settings]
    arch=x86_64
    build_type=Debug
    compiler=Visual Studio
    compiler.runtime=MDd
    compiler.version=17
    os=Windows

[full_requires]


[full_options]
    directx=False
    opengl=False
    opengles=False
    sdl2main=False
    shared=False
    vulkan=False

[recipe_hash]
    5d99981c667b8a9f3939c3cdc8f7e4a3

[env]
```
</details>

**Comment by ericLemanissier** [comment]
Can you update the recipe by using `-u` argument ? this seems to have been solved with https://github.com/conan-io/conan-center-index/pull/8609

**Comment by positivcheg94** [comment]
> Can you update the recipe by using `-u` argument ? this seems to have been solved with #8609

I’ve just migrated yesterday from sfml to sdl so it seems like an issue is still present as I’m fetching the latest version. If I use 2.0.16 though everything works fine and sdl_config.h has all video backends disabled.

**Comment by ericLemanissier** [comment]
The PR above has been merged 6 hours ago, so it's expected that you get this error if you did not update since yesterday.

**Comment by positivcheg94** [comment]
> The PR above has been merged 6 hours ago, so it's expected that you get this error if you did not update since yesterday.

Okay, can confirm that it works properly now!
